CDCgov/NEDSS-DataReporting

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/NotificationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

CNDIT-1584: Process the notifications along with the investigation data in post processing service.
Updated and ran all the unit tests

CNDIT-1584: Process the notifications along with the investigation data in post processing service.

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java

This PR includes fixes for the order of topics submission in investigation pre-processing service.
- **ProcessInvestigationDataUtil.java**: make the method for processing and sending notification data public
- **InvestigationService.java**: call processNotifications method after investigation topic has been sent
[CNDIT-1609](https://cdc-nbs.atlassian.net/browse/CNDIT-1609)

CNDIT-1609: Reorder notification topic submission

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java

Added listener on completion state for Investigation reporting topic. When the Investigation topic sending is complete, the related Notification data is processed and sent.
[CNDIT-1609](https://cdc-nbs.atlassian.net/browse/CNDIT-1609)

CNDIT-1609 (add): Sent notifications when investigation data sending completed

---

liquibase-service/src/main/resources/db/odse/020-fn_get_record_status-001.sql
liquibase-service/src/main/resources/db/rdb/019-fn_get_record_status-001.sql

Fixes the `fn_get_record_status` function to return `INACTIVE` value when the source column value = INACTIVE
[CNDIT-1586](https://cdc-nbs.atlassian.net/browse/CNDIT-1586)

CNDIT-1586 Fix fn_get_record_status to return for INACTIVE value

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Increases log detailing for RTR post-processing
[CNDIT-1587](https://cdc-nbs.atlassian.net/browse/CNDIT-1587)

CNDIT-1587: Increase logging to post-processing service

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java

Disabling the notification processing for debugging the looping issue.

Disabling the notification processing for debugging the looping issue.

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/config/LogDynamicFileAppenderConfig.java
ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/config/LogDynamicFileAppenderConfig.java
observation-service/src/main/java/gov/cdc/etldatapipeline/observation/config/LogDynamicFileAppenderConfig.java
organization-service/src/main/java/gov/cdc/etldatapipeline/organization/config/LogDynamicFileAppenderConfig.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/config/LogDynamicFileAppenderConfig.java

Fixes dynamic file name potential vulnerability in `LogDynamicFileAppenderConfig` for all services.
[CNDIT-1708](https://cdc-nbs.atlassian.net/browse/CNDIT-1708)

CNDIT-1708: Fix ATO security vulnerabilities for RTR services

---

liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb/tables/017-create_nrt_observation-002.sql

+ Addition of new columns to nrt_observation via alter statements

Observation model update for NRT tables

---

liquibase-service/src/main/resources/db/rdb/tables/012-create-nrt-investigation-notification-002.sql

Check to avoid renaming nrt_investigation_notification if it already exists.

Check for nrt-investigation-notification

---

.github/workflows/Build-and-deploy-reporting-services.yaml
.github/workflows/sonar.yaml
common-util/build.gradle
investigation-service/Dockerfile
investigation-service/build.gradle
ldfdata-service/Dockerfile
ldfdata-service/build.gradle
liquibase-service/build.gradle
observation-service/Dockerfile
observation-service/build.gradle
organization-service/Dockerfile
organization-service/build.gradle
person-service/Dockerfile
person-service/build.gradle
post-processing-service/Dockerfile
post-processing-service/build.gradle
status-service/Dockerfile
status-service/build.gradle

[7.6.0 Remediation Details](https://cdc-nbs.atlassian.net/wiki/x/jIATOQ)
[CNDIT-1786](https://cdc-nbs.atlassian.net/browse/CNDIT-1786)

CNDIT-1786: RTR: Fix the CVE Remediation evaluation issues

---

liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/routines/021_sp_observation_event-001.sql
liquibase-service/src/main/resources/db/rdb/tables/017-create_nrt_observation-003.sql
observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/dto/Observation.java
observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/dto/ObservationTransformed.java
observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationReporting.java
observation-service/src/main/java/gov/cdc/etldatapipeline/observation/service/ObservationService.java
observation-service/src/main/java/gov/cdc/etldatapipeline/observation/util/ProcessObservationDataUtil.java
observation-service/src/test/java/gov/cdc/etldatapipeline/observation/ObservationDataProcessTests.java
observation-service/src/test/java/gov/cdc/etldatapipeline/observation/service/ObservationServiceTest.java
observation-service/src/test/resources/rawDataFiles/FollowupObservations.json
observation-service/src/test/resources/rawDataFiles/ParentObservations.json

Updates Observation processing to extend its output for Montana reports
[CNDIT-1729](https://cdc-nbs.atlassian.net/browse/CNDIT-1729)

CNDIT-1729: Update observation services for Montana reports

---

liquibase-service/src/main/resources/db/rdb/tables/017-create_nrt_observation-003.sql

Fixes misprint in the `017-create_nrt_observation-003.sql` script.

CNDIT-1729: Minor fix for liquibase script

---

liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb/routines/007-sp_s_pagebuilder_postprocessing-002.sql
liquibase-service/src/main/resources/db/rdb/routines/010-sp_sld_investigation_repeat_postprocessing-002.sql
liquibase-service/src/main/resources/db/rdb/routines/013-sp_hepatitis_datamart_postprocessing-002.sql

`sp_s_pagebuilder_postprocessing` and `sp_sld_investigation_repeat_postprocessing` modified to pick only latest modified answers.

CNDIT-1730: procedure changes to pick only the latest page case answers

---

liquibase-service/src/main/resources/db/rdb/tables/001-create_data_sync_config-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation-003.sql

Remove GO keyword

---

liquibase-service/src/main/resources/db/rdb/routines/001-generate_data_for_data_sync_config-004.sql

updated nrt_observation_coded query

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-002.sql

- **Related story**: [CNDE-1745](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNDE/issues/CNDE-1745)

CNDE-1745: update to nrt_investigation_postprocessing

---

liquibase-service/src/main/resources/db/rdb_modern/routines/013-sp_hepatitis_datamart_postprocessing-002.sql

- **Related story**: [CNDE-1730]

CNDE-1730: fix to CTE

---

observation-service/src/main/java/gov/cdc/etldatapipeline/observation/util/ProcessObservationDataUtil.java
observation-service/src/test/java/gov/cdc/etldatapipeline/observation/ObservationDataProcessTests.java
observation-service/src/test/java/gov/cdc/etldatapipeline/observation/service/ObservationServiceTest.java
observation-service/src/test/resources/rawDataFiles/ParentObservations.json

Hot fix for reporting Observation `report_sprt_uid` and `report_refr_uid`.
- **Related story**: [CNDE-1805](https://cdc-nbs.atlassian.net/browse/CNDE-1805)

CNDE-1805 Fix for report_sprt_uid and report_refr_uid

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Added `nrt_observation` topic post-processing to call `sp_d_morbidity_report_postprocessing`, `sp_d_lab_test_postprocessing` and `sp_d_labtest_result_postprocessing` stored procs.
- **Related story**: 
[CNDE-1394](https://cdc-nbs.atlassian.net/browse/CNDE-1394)
[CNDE-1395](https://cdc-nbs.atlassian.net/browse/CNDE-1395)
[CNDE-1397](https://cdc-nbs.atlassian.net/browse/CNDE-1397)

CNDE-1394,1395,1397 Post-processing integration for Morbidity and Lab Test dimensions

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/013-sp_hepatitis_datamart_postprocessing-003.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/015-sp_nrt_morbidity_report_postprocessing-002.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/017-sp_d_labtest_result_postprocessing-002.sql

Featured Changes:
- Update operation is added for target dimensions in sp_d_labtest_result_postprocessing and sp_d_morbidity_report_postprocessing. Sprocs support both insert and update. 
- Tested on latest Observation Service. 
- Key generation for TEST_RESULT_GROUPING, RESULT_COMMENT_GROUP and  MORB_RPT_USER_COMMENT.
- Removal of global temporary tables and handling dynamic column assignment in Morb Report sproc using dynamic SQL. 
Additional:
- Hepatitis Datamart Additional Column Wiring for 
1. INIT_NND_NOT_DT
3. NOT_SUBMIT_DT
5. EVENT_DATE
7. EVENT_DATE_TYPE
_sp_d_labtest_result_postprocessing_
- LAB_TEST_RESULT
- TEST_RESULT_GROUPING
-  RESULT_COMMENT_GROUP
-  LAB_RESULT_VAL
-  LAB_RESULT_COMMENT
_sp_d_morbidity_report_postprocessing:_
- MORBIDITY_REPORT
- MORBIDITY_REPORT_EVENT
- …

CNDE-1819: Addition of Update and Key Generation to Lab Test Result and Morbidity Report Post-Processing, Wiring of Hepatitis Lab Columns 

---

liquibase-service/src/main/resources/db/rdb_modern/routines/016-sp_nrt_morbidity_report_postprocessing-002.sql

Rename stored procedure prefix for Liquibase.

Fix: Rename Morbidity Report Stored Procedure

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/InvestigationTransformed.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java

Fix for tombstone (clearing) message call order.
- **Related story**: [CNDE-1849](https://cdc-nbs.atlassian.net/browse/CNDE-1849)

CNDE-1849 Hot fix for tombstone message calls

---

liquibase-service/src/main/resources/db/rdb_modern/routines/019-sp_lab100_datamart_postprocessing-001.sql

Lab100 requires the parent LAB_UIDs to be present. Hence adding it to the first step in the sequence.
- **Related story**: [CNDE-1843](https://cdc-nbs.atlassian.net/browse/CNDE-1843)

CNDE-1843 | enhancement to handle RTR sequence

---

.github/workflows/Build-and-deploy-reporting-services.yaml
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

(Hotfix) CNDE-1843: Updating the liquibase changelog configuration to make the updates to existing stored proc scripts executable.
- Related story: [CNDE-1843](https://cdc-nbs.atlassian.net/browse/CNDE-1843)
-  Enhancement to handle RTR sequence PR#67 

CNDE-1843 - Updating the liquibase changelog configuration to make the updates to existing stored proc scripts executable.

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Enable runOnChange for Hepatitis Datamart stored procedure in rdb_modern changelog.
- CNDE-1848: [CNDE-1848](https://cdc-nbs.atlassian.net/browse/CNDE-1848)

CNDE-1848: Hot fix to add runOnChange for hepatitis datamart

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Investigation.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/InvestigationTransformed.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InvestigationReporting.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
investigation-service/src/test/resources/rawDataFiles/CaseCountInfo.json
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-002.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/021-sp_nrt_case_count_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/020-create_nrt_investigation-003.sql

SAS to SQL RTR: Migrating CASE_COUNT SAS dimension to SQL procedures
- **Related story**: [CNDE-1602](https://cdc-nbs.atlassian.net/browse/CNDE-1602)

CNDE-1602: SAS to SQL RTR: Migrate CASE_COUNT SAS dimension to SQL

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-003.sql

Name and minor fix for `nrt_investigation` modifying script.
- **Related story**: [CNDE-1602](https://cdc-nbs.atlassian.net/browse/CNDE-1602)

CNDE-1602: Hot fix for sql script

---

liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-003.sql

Change `IF EXISTS` to `IF NOT EXISTS` in table modifying script.

CNDE-1602: Minor but important SQL fix

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java

Fix to a field generated for nrt_investigation
- **Related story**: [CNDE-1602(https://cdc-nbs.atlassian.net/browse/CNDE-1602)

CNDE-1602: Fix for datetime field

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Postprocessing service integration for case_count
- **Related story**: [CNDE-1878](https://cdc-nbs.atlassian.net/browse/CNDE-1878)
- **Related story**: [CNDE-1602](https://cdc-nbs.atlassian.net/browse/CNDE-1602)

CNDE-1878: Postprocessing service integration for case_count

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Investigation.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-002.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/021-sp_nrt_case_count_postprocessing-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Incorporating few naming and refactoring changes for investigation -> casecount flow.
- **Related story**: [CNDE-1878](https://cdc-nbs.atlassian.net/browse/CNDE-1878)

CNDE-1878: Refactoring changes

---

liquibase-service/src/main/resources/db/rdb_modern/routines/010-sp_sld_investigation_repeat_postprocessing-002.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/012-sp_f_page_case_postprocessing-001.sql

Fix for investigation_form_cd error in RTR.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1902?atlOrigin=eyJpIjoiYWJhNGQ1MTI4YjA4NGVmMGFhYzEwMmM0YjA4ZWQzMTAiLCJwIjoiaiJ9)

CNDE-1902: Hot fix for investigation_form_cd

---

liquibase-service/Dockerfile

Update Liquibase Dockerfile for rdb_modern Views.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1863)

CNDE-1863: Update Dockerfile

---

common-util/src/main/java/gov/cdc/etldatapipeline/commonutil/json/CustomJsonGeneratorImpl.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Interview.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InterviewNote.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InterviewReporting.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InterviewReportingKey.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
investigation-service/src/test/resources/rawDataFiles/InterviewNotes.json

Added fields required and fixed issues found during integrated testing
- **Related story**: [CNDE-1908](url)

CNDE-1908: Code Fix

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-001.sql

Update nrt_investigation table earlier in the Liquibase deployment. 

Liquibase fix

---

liquibase-service/src/main/resources/db/rdb_modern/routines/020-sp_lab101_datamart_postprocessing-001.sql

Column "NARMS_EXPECTED_SHIPDATE" in dbo.LAB101 was not populating. This PR will fix that.
- **Related story**: [CNDE-1945](https://cdc-nbs.atlassian.net/browse/CNDE-1945)

CNDE-1945: LAB101 Bugfix

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

For `nrt_interview` topic post-processing: add calls for `sp_d_interview_postprocessing` and `sp_f_interview_case_postprocessing` stored procedures.

CNDE-1912: Post-processing integration for D_Interview and F_Interview_Case

---

liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_date-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_numeric-001.sql

Fix Liquibase column addition script.
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1916)

CNDE-1916: Hotfix for new nrt obs columns

---

liquibase-service/src/main/resources/db/rdb_modern/routines/025-sp_f_std_page_case_postprocessing-001.sql

Basic refactoring and added nolock on the dims and lookup tables.
- **Related story**: [CNDE-1950](url)

CNDE-1950: F_STD_PAGE_CASE Postprocessing Proc refactored

---

liquibase-service/src/main/resources/db/rdb_modern/routines/025-sp_f_std_page_case_postprocessing-001.sql

Hotfix to correct column rename.
- **Related story**: [CNDE-1950](url)

CNDE-1950: Renamed column

---

investigation-service/src/main/resources/application.yaml
ldfdata-service/src/main/resources/application.yaml
observation-service/src/main/resources/application.yaml
organization-service/src/main/resources/application.yaml
person-service/src/main/resources/application.yaml
post-processing-service/src/main/resources/application.yaml

CNDE-1982: Update port information

---

db/upgrade/rdb_modern/routines/011-sp_f_page_case_postprocessing.sql
db/upgrade/rdb_modern/routines/024-sp_f_std_page_case_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/012-sp_f_page_case_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/025-sp_f_std_page_case_postprocessing-001.sql

This includes the following fixes:
- Align F_PAGE_CASE proc to use Look up tables to capture the correct Keys
- Performance improvement to both F_PAGE_CASE and F_STD_PAGE_CASE procedures
- **Related story**: [CNDE-2016](https://cdc-nbs.atlassian.net/browse/CNDE-2016)

CNDE-2016: Fixed JOIN issue and refactored for performance

---

db/upgrade/odse/routines/014-sp_public_health_case_fact_datamart_event.sql
liquibase-service/src/main/resources/db/odse/routines/018-sp_public_health_case_fact_datamart_event-001.sql

Temporary change to procedure to avoid RTR and Classic batch job from updating PHCF table
- **Related story**: [CNDE-2033](https://cdc-nbs.atlassian.net/browse/CNDE-2033)

CNDE-2033: Updates to proc to handle collision with existing table

---

liquibase-service/src/main/resources/db/rdb_modern/tables/012-create_nrt_investigation_notification-001.sql

Liquibase fix for `012-create_nrt_investigation_notification-001.sql`

RTR - hot fix for nrt_investigation_notification script

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
db/upgrade/rdb_modern/tables/007-create_nrt_investigation.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Investigation.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InvestigationReporting.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-001.sql

Removing redundant and unused columns
- **Related story**: [CNDE-1968](https://cdc-nbs.atlassian.net/browse/CNDE-1968)

CNDE-1968: Removing redundant columns

---

liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation-001.sql

Fix `nrt_observation` table create/update.

RTR - hot fix for nrt_observation script

---

liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-001.sql

Corrected the alter query
- **Related story**: [CNDE-1968](url)

CNDE-1968: Corrected the alter query

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql

CNDE-1971 detection_method_desc_txt null fix

---

db/upgrade/rdb_modern/routines/004-sp_nrt_investigation_postprocessing.sql
db/upgrade/rdb_modern/routines/005-sp_nrt_notification_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/model/DatamartData.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/ProcessDatamartData.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/DatamartProcessingTest.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Resolve the data gap issue in Hepatitis Datamart when a related Notification is updated.
- **Related story**: [CNDE-1943](https://cdc-nbs.atlassian.net/browse/CNDE-1943)

CNDE-1943: Add Datamart update in Notification post-processing

---

db/upgrade/rdb_modern/routines/024-sp_f_std_page_case_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/025-sp_f_std_page_case_postprocessing-001.sql

Investigation was missed when no association to any of the page builder columns where present. This has been fixed.
- **Related story**: [CNDE-2063](https://cdc-nbs.atlassian.net/browse/CNDE-2063)]

CNDE-2063: Fixed issue of missed STD records

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

- **Related story**: [CNDE-2055](https://cdc-nbs.atlassian.net/browse/CNDE-2055)

CNDE-2055: Post-process service integration for RDB D_PLACE

---

liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Wire in User profile components for Liquibase
- **Related story**: [2048](https://cdc-nbs.atlassian.net/browse/CNDE-2048)

CNDE-2048: User profile hotfix for Liquibase

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Added post processing service for user profile by calling user profile post processing SP
- **Related story**: [CNDE-2169](https://cdc-nbs.atlassian.net/browse/CNDE-2169)

CNDE-2169 user profile java service

---

liquibase-service/src/main/resources/db/rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/DatamartProcessingTest.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
post-processing-service/src/test/resources/rawDataFiles/MeaslesCaseDatamart.json

Measles_Case post processing service integration
- **Related story**: [CNDE-2091](https://cdc-nbs.atlassian.net/browse/CNDE-2091)

CNDE-2091: Measles_Case post processing service integration

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

The path for sp_measles_case_datamart_postprocessing was incorrect in the rdb_modern changelog. This PR contains the fix for that issue.
- **Related story**: [CNDE-2200](https://cdc-nbs.atlassian.net/browse/CNDE-2200)

CNDE-2200: Correction for measles case sproc in rdb_modern changelog

---

db/upgrade/rdb_modern/tables/017-create_nrt_observation_coded.sql
db/upgrade/rdb_modern/tables/017-create_nrt_observation_date.sql
db/upgrade/rdb_modern/tables/017-create_nrt_observation_edx.sql
db/upgrade/rdb_modern/tables/017-create_nrt_observation_material.sql
db/upgrade/rdb_modern/tables/017-create_nrt_observation_numeric.sql
db/upgrade/rdb_modern/tables/017-create_nrt_observation_reason.sql
db/upgrade/rdb_modern/tables/017-create_nrt_observation_txt.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_coded-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_date-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_edx-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_material-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_numeric-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_reason-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_txt-001.sql

Removing rdb_modern references from nrt_observation child tables' create scripts. 
- **CNDE-2201**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2201)

Remove rdb_modern reference from nrt table create

---

db/upgrade/rdb_modern/routines/004-sp_nrt_investigation_postprocessing.sql
db/upgrade/rdb_modern/routines/005-sp_nrt_notification_postprocessing.sql
db/upgrade/rdb_modern/routines/015-sp_nrt_morbidity_report_postprocessing.sql
db/upgrade/rdb_modern/routines/016-sp_d_labtest_result_postprocessing.sql
db/upgrade/rdb_modern/tables/019-create_nrt_datamart_metadata.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/016-sp_nrt_morbidity_report_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/017-sp_d_labtest_result_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/model/DatamartData.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/model/DatamartDataId.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/model/dto/Datamart.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/ProcessDatamartData.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/DatamartProcessingTest.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
post-processing-service/src/test/resources/rawDataFiles/CRSCaseDatamart.json
post-processing-service/src/test/resources/rawDataFiles/CaseLabDatamart.json
post-processing-service/src/test/resources/rawDataFiles/GenericCaseDatamart.json
post-processing-service/src/test/resources/rawDataFiles/HepDatamart.json
post-processing-service/src/test/resources/rawDataFiles/RubellaCaseDatamart.json
post-processing-service/src/test/resources/rawDataFiles/StdDatamart.json

For `CASE_LAB_DATAMART` add sp procedure call, refactor relevant stored procedures to return datamart metadata, update and refactor unit tests.
- Refactored sp: `sp_nrt_investigation_postprocessing`, `sp_nrt_notification_postprocessing`, `sp_d_morbidity_report_postprocessing`, `sp_d_labtest_result_postprocessing`
- PostProcessingService: CASE_LAB_DATAMART integration; make it run before HEPATITIS_DATAMART
- ProcessDatamartData: special processing when both `HEPATITIS_DATAMART` and `CASE_LAB_DATAMART` exist for the same case
- Unit tests: multiple similar tests to enhance maintainability and reduce redundancy, add tests for `CASE_LAB_DATAMART`
- **Related story**: [CNDE-2057](https://cdc-nbs.atlassian.net/browse/CNDE-2057)

CNDE-2057: Post-processing integration for CASE_LAB_DATAMART

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql

Wire in required Investigation columns for SAS to SQL migration of D_INV_PLACE_REPEAT/Repeated_Place_Dimension.sas
- **CNDE-2109 story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2108)
- **CNDE-2192 story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2192)

CNDE-2108: Wire in Investigation pre-processing column for D_INV_PLACE_REPEAT

---

db/upgrade/odse/routines/020-sp_contact_record_event.sql
db/upgrade/odse/views/003-v_rdb_ui_metadata_answers_contact.sql
liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/routines/025-sp_contact_record_event-001.sql
liquibase-service/src/main/resources/db/odse/views/003-v_rdb_ui_metadata_answers_contact-001.sql

Preprocessing stored procedure and related assets for populating contact records and tracing information into the staging tables.
- **Related story**: [CNDE-2144](https://cdc-nbs.atlassian.net/browse/CNDE-2144)

CNDE-2144: Contact_Records preprocessing procedure

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Fix for names in rdb_modern changelog, causing execution of Liquibase scripts to fail.
- **Related story**: [CNDE-2251](https://cdc-nbs.atlassian.net/browse/CNDE-2251)

CNDE-2251: fix names in rdb_modern changelog

---

db/upgrade/rdb_modern/tables/019-create_nrt_datamart_metadata.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/DatamartProcessingTest.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
post-processing-service/src/test/resources/rawDataFiles/BMIRDCaseDatamart.json

BMIRD_CASE post process java service and unit test
- **Related story**: [CNDE-2090](https://cdc-nbs.atlassian.net/browse/CNDE-2090)

CNDE-2090: BMIRD_CASE post process java service + unit test

---

db/upgrade/rdb_modern/routines/022-sp_d_interview_postprocessing.sql
db/upgrade/rdb_modern/routines/035-sp_d_contact_record_postprocessing.sql
db/upgrade/rdb_modern/routines/036-sp_event_metric_datamart_postprocessing.sql
db/upgrade/rdb_modern/routines/037-sp_f_contact_record_case_postprocessing.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/023-sp_d_interview_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/036-sp_d_contact_record_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/037-sp_event_metric_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/038-sp_f_contact_record_case_postprocessing-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Post-process F_Contact_Record_Case procedure to populate F_CONTACT_RECORD_CASE and also the service integration for it.
- **Related story**: [CNDE-2146](https://cdc-nbs.atlassian.net/browse/CNDE-2146)

CNDE-2146: F_CONTACT_RECORD_CASE

---

db/upgrade/rdb_modern/tables/025-create_nrt_srte_totalidm.sql
db/upgrade/rdb_modern/tables/026-create_nrt_srte_IMRDBMapping.sql
db/upgrade/rdb_modern/tables/028-create_nrt_srte_Condition_code.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/025-create_nrt_srte_totalidm-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/026-create_nrt_srte_IMRDBMapping-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/028-create_nrt_srte_Condition_code-001.sql

Added a fix for three of the SRTE table structure to sink to `rdb_modern`.
```
nrt_srte_totalidm
nrt_srte_IMRDBMapping
nrt_srte_Condition_code
```
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2206)

[CNDE-2206] Fixing srte table structure for rdb_modern

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java

Quick fix for naming issue causing sp_event_metric_datamart_postprocessing to not be triggered
- **Related story**: [CNDE-2257](https://cdc-nbs.atlassian.net/browse/CNDE-2257)
- [] Is the screenshot attached for code coverage?

CNDE-2257: Fix event metric proc name in PostProcRepository

---

liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb/routines/001-generate_data_for_data_sync_config-001.sql
liquibase-service/src/main/resources/db/rdb/tables/002-alter_lab_test-001.sql
liquibase-service/src/main/resources/db/rdb/tables/003-alter_data_sync_config_drop_col-001.sql
liquibase-service/src/main/resources/db/rdb/tables/004-create_data_sync_config_log-001.sql

DATASYNC: added extra db config for data sync

---

db/upgrade/rdb_modern/tables/039-alter_table_add_index.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/tables/039-alter_table_add_index-001.sql

Fix for failing index creation - idx_interview_uid_rdb_column inn liquibase and consolidated script

Fix for failing index creation - idx_interview_uid_rdb_column inn liquibase and consolidated script 

---

liquibase-service/src/main/resources/db/rdb/tables/001-create_data_sync_config-001.sql
liquibase-service/src/main/resources/db/rdb/tables/004-create_data_sync_config_log-001.sql

DataSync fix update

---

liquibase-service/src/main/resources/db/rdb/tables/001-create_data_sync_config-001.sql
liquibase-service/src/main/resources/db/rdb/tables/004-create_data_sync_config_log-001.sql

DataSync: update

---

liquibase-service/src/main/resources/db/changelog/db.srte.changelog-16.1.yaml
liquibase-service/src/main/resources/db/srte/tables/002-alter_imrdbmapping-001.sql

Fix for failing insert in IMRDBMapping

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java

Fix unit tests for Interview
- **Related story**: [CNDE-2277](https://cdc-nbs.atlassian.net/browse/CNDE-2277)

CNDE-2277: Fix unit tests for Kafka tombstone refactoring

---

db/upgrade/rdb_modern/tables/039-alter_table_add_index.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/tables/039-alter_table_add_index-001.sql

Cnde 2279 - add new index dbo.nrt_observation_coded (observation_uid, ovc_code);

---

liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml

DataSync: comment change set for data sync

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Fixed topic name for user profile to actual value `nrt_auth_user`.
- **Related story**: [CNDE-2286](https://cdc-nbs.atlassian.net/browse/CNDE-2286)

CNDE-2286: User_profile hydration issue

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Fixed name for user uid field in user profile payload.
- **Related story**: [CNDE-2286](https://cdc-nbs.atlassian.net/browse/CNDE-2286)

CNDE-2286: Fix uid name in user profile payload

---

investigation-service/src/main/resources/application.yaml

Minor fix to correct the naming of the Kafka topic defined in application properties.
- **Related story**: CNDE-2147

CNDE-2147: Fixed the kafka topic name

---

liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml

DataSync RDB Liquibase: uncommented rdb changelog

---

db/upgrade/rdb_modern/routines/039-sp_bmird_case_datamart_postprocessing.sql
db/upgrade/rdb_modern/tables/043-create_nrt_antimicrobial_group_key.sql
db/upgrade/rdb_modern/tables/044-create_nrt_antimicrobial_key.sql
db/upgrade/rdb_modern/tables/045-create_nrt_bmird_multi_val_group_key.sql
db/upgrade/rdb_modern/tables/046-create_nrt_bmird_multi_val_key.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/040-sp_bmird_case_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/043-create_nrt_antimicrobial_group_key-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/044-create_nrt_antimicrobial_key-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/045-create_nrt_bmird_multi_val_group_key-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/046-create_nrt_bmird_multi_val_key-001.sql

Migrated `BMIRD_Case` SAS to SQL stored procedure; integrated the necessary NRT key tables.
- sp_bmird_case_datamart_postprocessing
- nrt_antimicrobial_group_key
- nrt_antimicrobial_key
- nrt_bmird_multi_val_group_key
- nrt_bmird_multi_val_key
- **Related story**: [CNDE-2289](https://cdc-nbs.atlassian.net/browse/CNDE-2289)

CNDE-2289: BMIRD_Case SAS to SQL postprocessing migration 

---

db/upgrade/rdb_modern/routines/037-sp_f_contact_record_case_postprocessing.sql
db/upgrade/rdb_modern/tables/038-create_nrt_contact_key.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/038-sp_f_contact_record_case_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/038-create_nrt_contact_key-001.sql

Code fix needed for liquibase SQL file and procedure
- **Related story**: CNDE-2149

Code fix: Procedure and SQL files

---

liquibase-service/src/main/resources/db/rdb/routines/001-generate_data_for_data_sync_config-001.sql

DATASYNC: fix covid data mart and treatment record

---

liquibase-service/src/main/resources/db/rdb/routines/001-generate_data_for_data_sync_config-001.sql

DATASYNC: update var pam ldf

---

db/upgrade/rdb_modern/views/009-v_codeset.sql
db/upgrade/rdb_modern/views/010-v_code_value_general.sql
db/upgrade/rdb_modern/views/011-v_condition_dim.sql
liquibase-service/src/main/resources/db/rdb_modern/views/009-v_codeset-001.sql
liquibase-service/src/main/resources/db/rdb_modern/views/010-v_code_value_general-001.sql
liquibase-service/src/main/resources/db/rdb_modern/views/011-v_condition_dim-001.sql

nrt_srte_<table> all sync'd to rdb_modern with change Capture.

Use nrt_srte_<table> reference to these Views

---

db/upgrade/rdb_modern/routines/012-sp_hepatitis_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/013-sp_hepatitis_datamart_postprocessing-001.sql

Cnde 2244 - Avoid deadlock by excluding parallelism

---

db/upgrade/rdb_modern/routines/004-sp_nrt_investigation_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-001.sql

Fix to the procs to accomodate the correct Inv rows
- **Related story**: CNDE-2296

Fix to the procs to accomodate the correct Inv rows

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Contact.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/ContactReporting.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/utils/TestUtils.java

- **Related story**: [CNDE-2310](https://cdc-nbs.atlassian.net/browse/CNDE-2310)

Fix for Subject Key in Contact processing

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Integrate `sp_inv_summary_datamart_postprocessing` post-process procedure into java service.
- **Related story**: [CNDE-2153](https://cdc-nbs.atlassian.net/browse/CNDE-2153)

CNDE-2153: post-processing integration

---

db/upgrade/rdb_modern/views/001-v_getobscode.sql
db/upgrade/rdb_modern/views/004-v_getobstxt.sql
db/upgrade/rdb_modern/views/013-v_rdb_obs_mapping.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/views/001-v_getobscode-001.sql
liquibase-service/src/main/resources/db/rdb_modern/views/004-v_getobstxt-001.sql
liquibase-service/src/main/resources/db/rdb_modern/views/013-v_rdb_obs_mapping-001.sql

Two bugfixes in this PR:
- Added `batch_id` logic as necessary into the joins for the views that get data for legacy cases 
- Added always NULL rows to `v_rdb_obs_mapping` in order to always have all columns included for pivots in legacy case procedures
- **Related story**: [CNDE-2351](https://cdc-nbs.atlassian.net/browse/CNDE-2351)
- **Related story**: [CNDE-2352](https://cdc-nbs.atlassian.net/browse/CNDE-2352)
- **Related story**: [CNDE-2353](https://cdc-nbs.atlassian.net/browse/CNDE-2353)

CNDE-2351,2352,2353: update to legacy case join logic, v_rdb_obs_mapping

---

post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

removed space in test for build issue

---

db/upgrade/odse/000-odse-db-general.sql
db/upgrade/srte/000-srte-db-general.sql
liquibase-service/src/main/resources/db/changelog/db.odse.admin.tasks.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/000-odse-db-general-001.sql
liquibase-service/src/main/resources/db/srte/000-srte-db-general-001.sql

Added ODSE/SRT cdc scripts to Liquibase for Treatment
- **Related story**: [CNDE-2359](https://cdc-nbs.atlassian.net/browse/CNDE-2359)

Added ODSE/SRT cdc scripts to Liquibase for Treatment

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Contact.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/ContactReporting.java

Adding an attribute that is needed by event_metric.
- **Related story**: CNDE-2094

CNDE-2094: Fix to add interdependent attribute

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
liquibase-service/src/main/resources/db/rdb_modern/tables/042-create_nrt_treatment-001.sql

Added listener for treatment and updated output schema
- **Related story**: [CNDE-2341](https://cdc-nbs.atlassian.net/browse/CNDE-2341)

Hotfix for treatment listener 

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Treatment.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java

Fix for kafka sync error and added missing column
- **Related story**: [CNDE-2341](https://cdc-nbs.atlassian.net/browse/CNDE-2341)

Fix for kafka sync error and added missing column

---

liquibase-service/src/main/resources/db/changelog/db.rdb.changelog-16.1.yaml

removed data sync related from change log

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Changelog fix for CNDE-2345 
- **Related story**: [CNDE-2345](https://cdc-nbs.atlassian.net/browse/CNDE-2345)

CNDE-2345-hotfix

---

db/upgrade/rdb_modern/tables/028-create_nrt_srte_Condition_code.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/028-create_nrt_srte_Condition_code-001.sql

Wrap nrt_srte_Condition_code within begin end statement

Condition_Code: Add index into code block

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/main/resources/application.yaml
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

… d_tb_hiv
Feature flags added for release.
Pre-processing:
- TREATMENT
Post-processing:
- D_TB_HIV
- MORBIDITY_REPORT_DATAMART
- INV_SUMMARY_DATAMART

CNDE-2404: Feature flags for 7.9.0 release

---

db/upgrade/odse/routines/015-sp_notification_event.sql
liquibase-service/src/main/resources/db/odse/routines/020-sp_notification_event-001.sql

Update sp_notification_event to align with Investigation Notification for Summary Case Report and Aggregate Datamart. 

Align Notification with Investigation Notification

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Add feature flags to control Summary, SR100 and Aggregate reports execution.
PostProcessingService:
- summary-report-enable
- aggregate-report-enable
- **Related story**: [CNDE-2404](https://cdc-nbs.atlassian.net/browse/CNDE-2404)

CNDE-2404: Additional feature flagging for Summary, Aggregate and SR100

---

db/upgrade/rdb_modern/routines/001-sp_nrt_organization_postprocessing.sql
db/upgrade/rdb_modern/routines/002-sp_nrt_provider_postprocessing.sql
db/upgrade/rdb_modern/routines/003-sp_nrt_patient_postprocessing.sql
db/upgrade/rdb_modern/routines/004-sp_nrt_investigation_postprocessing.sql
db/upgrade/rdb_modern/routines/005-sp_nrt_notification_postprocessing.sql
db/upgrade/rdb_modern/routines/006-sp_s_pagebuilder_postprocessing.sql
db/upgrade/rdb_modern/routines/009-sp_sld_investigation_repeat_postprocessing.sql
db/upgrade/rdb_modern/routines/021-sp_nrt_case_management_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/002-sp_nrt_organization_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/003-sp_nrt_provider_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/004-sp_nrt_patient_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/007-sp_s_pagebuilder_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/010-sp_sld_investigation_repeat_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/022-sp_nrt_case_management_postprocessing-001.sql

Removed the full table deletes on the key tables to retain it. Also removed the filter that was used for page cases to pick latest changes since we now use batch id.
- **Related story**: CNDE-2258

CNDE-2258_p2

---

db/upgrade/rdb_modern/routines/145-sp_nrt_d_disease_site_postprocessing.sql
db/upgrade/rdb_modern/routines/146-sp_nrt_d_addl_risk_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/145-sp_nrt_d_disease_site_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/146-sp_nrt_d_addl_risk_postprocessing-001.sql

- **Related story**: [CNDE-2406](https://cdc-nbs.atlassian.net/browse/CNDE-2406)

CNDE 2406 - BugFix - Handling deletes/updates for d_disease_site & d_addl_risk

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
db/upgrade/rdb_modern/tables/014-create_nrt_page_case_answer.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/PageCaseAnswer.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/resources/rawDataFiles/InvestigationCaseAnswers.json
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/014-create_nrt_page_case_answer-001.sql

This ticket includes pre-processing changes for VAR cases
- **Related story**: [CNDE-2423](https://cdc-nbs.atlassian.net/browse/CNDE-2423)

CNDE-2423 - Preprocessing changes for VAR cases

---

db/upgrade/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing.sql
db/upgrade/rdb_modern/routines/120-sp_dyn_dm_provider_data_postprocessing.sql
db/upgrade/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing.sql
db/upgrade/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing.sql
db/upgrade/rdb_modern/routines/135-sp_dyn_dm_org_data_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/120-sp_dyn_dm_provider_data_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/135-sp_dyn_dm_org_data_postprocessing-001.sql

Made the stored procedure runs without any errors.
- **Related story**: 
- [CNDE-2365](https://cdc-nbs.atlassian.net/browse/CNDE-2365)

[CNDE-2365] - Test and validate converted Dyn Datamart sprocs with DM_INV_GENERIC_V2

---

db/upgrade/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing-001.sql

Dynamic datamart ran from main SP error fix
- **Related story**: [CNDE-2365](https://cdc-nbs.atlassian.net/browse/CNDE-2365)

[CNDE-2365] - Error Fix for invest form while ran from main SP

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
db/upgrade/rdb_modern/tables/014-create_nrt_page_case_answer.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/PageCaseAnswer.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/resources/rawDataFiles/InvestigationCaseAnswers.json
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/014-create_nrt_page_case_answer-001.sql

This ticket includes pre-processing changes for PAM_LDF
- **Related story**: [CNDE-2450](https://cdc-nbs.atlassian.net/browse/CNDE-2450)

CNDE-2450 Preprocessing Changes for PAM_LDF

---

db/upgrade/odse/views/005-v_rdb_ui_metadata_answers_vaccination.sql
liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/views/005-v_rdb_ui_metadata_answers_vaccination-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

This includes just the hotfix needed to deploy the missing view for Vac preprocessing.
- **Related story**: CNDE-2191

Hot Fix: Vaccination pre-processing

---

investigation-service/build.gradle
ldfdata-service/build.gradle
liquibase-service/build.gradle
observation-service/build.gradle
organization-service/build.gradle
person-service/build.gradle
post-processing-service/build.gradle
status-service/build.gradle

Spring boot version upgraded to 3.4.4
- **Related story**: CNDE-2472

Spring boot version upgraded to 3.4.4

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql

CNDE-2423 hotfix changes for investigation preprocessing
- **Related story**: [CNDE-2423](https://cdc-nbs.atlassian.net/browse/CNDE-2423)

CNDE-2423 hotfix changes for investigation preprocessing

---

liquibase-service/Dockerfile

clean up after removed MSGOUTE and DI

---

db/upgrade/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing.sql
db/upgrade/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing-001.sql

RTR Dynamic Datamarts: Make output tables for sprocs unique with datamart and batch_id
- **Related story**: [CNDE-2439](https://cdc-nbs.atlassian.net/browse/CNDE-2439)

[CNDE-2439] - RTR Dynamic Datamarts: Make output tables for sprocs unique with datamart and batch_id

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Update to rdb_modern changelog to remove duplicate id
- **CNDE-2418**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2418)

CNDE-2418: Changelog update

---

db/upgrade/rdb_modern/tables/190-create_nrt_odse_page_cond_mapping.sql
db/upgrade/rdb_modern/tables/191-create_nrt_odse_nbs_page.sql
db/upgrade/rdb_modern/tables/192-create_nrt_odse_nbs_ui_metadata.sql
db/upgrade/rdb_modern/tables/193-create_nrt_odse_nbs_rdb_metadata.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/190-create_nrt_odse_page_cond_mapping-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/191-create_nrt_odse_nbs_page-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/192-create_nrt_odse_nbs_ui_metadata-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/193-create_nrt_odse_nbs_rdb_metadata-001.sql

Fixes table references for indexes
- **Related story**: [CNDE-2340](https://cdc-nbs.atlassian.net/browse/CNDE-2340)

CNDE-2340: hot fix for index refs

---

db/upgrade/rdb_modern/routines/043-sp_inv_summary_datamart_postprocessing.sql
db/upgrade/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing.sql
db/upgrade/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing.sql
db/upgrade/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing.sql
db/upgrade/rdb_modern/routines/205-sp_dyn_dm_repeatvarch_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/045-sp_inv_summary_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/205-sp_dyn_dm_repeatvarch_postprocessing-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/main/resources/application.yaml
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

Adding integration into Java service to call the dyn datamarts and also some additional refactoring and optimization for procedures.
- **Related story**: [CNDE-2446](https://cdc-nbs.atlassian.net/browse/CNDE-2446)

CNDE-2446: Java service update for dyn datamarts (Part 1)

---

db/upgrade/rdb_modern/routines/120-sp_dyn_dm_provider_data_postprocessing.sql
db/upgrade/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing.sql
db/upgrade/rdb_modern/routines/135-sp_dyn_dm_org_data_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/120-sp_dyn_dm_provider_data_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/135-sp_dyn_dm_org_data_postprocessing-001.sql

RTR Dyn Datamart: Make output tables for sprocs unique with datamart and batch_id (PART 2)
- **Related story**: [CNDE-2440](https://cdc-nbs.atlassian.net/browse/CNDE-2440)

[CNDE-2440] - RTR Dyn Datamart: Make output tables for sprocs unique with datamart and batch_id

---

db/upgrade/rdb_modern/routines/150-sp_summary_report_case_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/150-sp_summary_report_case_postprocessing-001.sql

Limit investigations processed by Summary Report Case post-processing to case_type_cd = 'S'.  
- **CNDE-2486**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2486)

CNDE-2486: Add condition to process only summary report cases

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Fix liquibase errors.

---

investigation-service/Dockerfile
ldfdata-service/Dockerfile
liquibase-service/Dockerfile
observation-service/Dockerfile
organization-service/Dockerfile
person-service/Dockerfile
post-processing-service/Dockerfile
status-service/Dockerfile

Address the CVE vulnerabilities and patch

Address the CVE vulnerabilities and patch

---

db/upgrade/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing.sql
db/upgrade/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/115-sp_dyn_dm_invest_form_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing-001.sql

Code fixes to upstream procs in the dynamic datamart process which was identified through integrated testing
- **Related story**: [CNDE-2513](https://cdc-nbs.atlassian.net/browse/CNDE-2513)

CNDE-2513: Code fixes to upstream procs in the dynamic data mart process

---

db/upgrade/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing.sql
db/upgrade/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing.sql
db/upgrade/rdb_modern/routines/225-sp_dyn_dm_main_postprocessing.sql
db/upgrade/rdb_modern/routines/235-sp_dyn_dm_repeatnumeric_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/125-sp_dyn_dm_page_builder_d_inv_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/225-sp_dyn_dm_main_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/235-sp_dyn_dm_repeatnumeric_postprocessing-001.sql

Code fixes to upstream procs in the dynamic data mart process.
- **Related story**: [CNDE-2513](https://cdc-nbs.atlassian.net/browse/CNDE-2513)
- **Related story**: [CNDE-2372](https://cdc-nbs.atlassian.net/browse/CNDE-2372)

CNDE-2372: Fix to the procs identified through integrated testing

---

db/upgrade/rdb_modern/routines/047-sp_bmird_strep_pneumo_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/140-sp_bmird_strep_pneumo_datamart_postprocessing-001.sql

Quick fix to resolve the issue with field S_I_R_U_RESULT_8 in BMIRD_STREP_PNEUMO_DATAMART
- **Related story**: [CNDE-2424](https://cdc-nbs.atlassian.net/browse/CNDE-2424)

CNDE-2424: Fix for field: S_I_R_U_RESULT_8

---

db/upgrade/rdb_modern/routines/016-sp_d_labtest_result_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/017-sp_d_labtest_result_postprocessing-001.sql

Fix for multiple investigations associated to a single lab report. 
- Maintain investigation history.
- Use new associated_phc_uids in nrt_observation for data freshness. 
- Align sproc with latest design updates. 
- **CNDE-2510**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2510)

CNDE-2510: Bugfix for multiple investigation associated to lab reports

---

.github/workflows/Build-and-deploy-reporting-services.yaml

update token permissions

---

liquibase-service/src/main/resources/db/rdb_modern/tables/042-create_nrt_treatment-001.sql

Fix drop column statement for Liquibase

Liquibase: Fix drop column statement

---

db/upgrade/odse/routines/011-sp_ldf_phc_event.sql
db/upgrade/odse/routines/013-sp_ldf_data_event.sql
db/upgrade/rdb_modern/routines/285-sp_ldf_bmird_datamart_postprocessing.sql
db/upgrade/rdb_modern/tables/238-create_ldf_bmird.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/routines/015-sp_ldf_phc_event-001.sql
liquibase-service/src/main/resources/db/odse/routines/017-sp_ldf_data_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/285-sp_ldf_bmird_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/238-create_ldf_bmird-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

This ticket includes post-processing changes for LDF_BMIRD
- **Related story**: [CNDE-2493](https://cdc-nbs.atlassian.net/browse/CNDE-2493)

CNDE-2493 - Postprocessing Changes for LDF_BMIRD

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java

Bug for confirmation_method_group's confirmation_method_time.
- Removed logic assigning null values to phc last_chg_time aligning with baseline SAS.
- **CNDE-2556**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2556)

CNDE-2556: Fix confirmation method time logic in post-processing logic 

---

db/upgrade/odse/routines/004-sp_patient_event.sql
db/upgrade/odse/routines/006-sp_investigation_event.sql
db/upgrade/rdb_modern/tables/005-create_nrt_patient.sql
db/upgrade/rdb_modern/tables/007-create_nrt_investigation.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Investigation.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InvestigationReporting.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
liquibase-service/src/main/resources/db/odse/routines/008-sp_patient_event-001.sql
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/005-create_nrt_patient-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-001.sql
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/PersonExtendedProps.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/patient/PatientElasticSearch.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/patient/PatientReporting.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/persondetail/Name.java
person-service/src/test/java/gov/cdc/etldatapipeline/person/PersonDataPostProcessingTests.java
person-service/src/test/resources/rawDataFiles/patient/PatientElastic.json
person-service/src/test/resources/rawDataFiles/patient/PatientReporting.json

This PR includes preprocessing changes for Covid marts specifically COVID_CASE_DATAMART.
- investigation preprocessing to include notes
- person preprocessing to include a patient's name related attributes
- **Related story**: [CNDE-2498](https://cdc-nbs.atlassian.net/browse/CNDE-2498)

CNDE-2498: Preprocessing changes for Covid marts

---

db/upgrade/rdb_modern/routines/145-sp_nrt_d_disease_site_postprocessing.sql
db/upgrade/rdb_modern/routines/146-sp_nrt_d_addl_risk_postprocessing.sql
db/upgrade/rdb_modern/routines/156-sp_nrt_d_move_cntry_postprocessing.sql
db/upgrade/rdb_modern/routines/170-sp_nrt_d_gt_12_reas_postprocessing.sql
db/upgrade/rdb_modern/routines/175-sp_nrt_d_move_cnty_postprocessing.sql
db/upgrade/rdb_modern/routines/180-sp_nrt_d_hc_prov_ty_3_postprocessing.sql
db/upgrade/rdb_modern/routines/185-sp_nrt_d_move_state_postprocessing.sql
db/upgrade/rdb_modern/routines/190-sp_nrt_d_out_of_cntry_postprocessing.sql
db/upgrade/rdb_modern/routines/195-sp_nrt_d_moved_where_postprocessing.sql
db/upgrade/rdb_modern/routines/200-sp_nrt_d_smr_exam_ty_postprocessing.sql
db/upgrade/rdb_modern/routines/215-sp_nrt_d_var_pam_postprocessing.sql
db/upgrade/rdb_modern/routines/225_sp_nrt_d_rash_loc_gen_postprocessing.sql
db/upgrade/rdb_modern/routines/230-sp_nrt_d_pcr_source_postprocessing.sql
db/upgrade/rdb_modern/routines/235-sp_nrt_var_pam_ldf_postprocessing.sql
db/upgrade/rdb_modern/routines/250-sp_var_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/145-sp_nrt_d_disease_site_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/146-sp_nrt_d_addl_risk_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/156-sp_nrt_d_move_cntry_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/170-sp_nrt_d_gt_12_reas_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/175-sp_nrt_d_move_cnty_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/180-sp_nrt_d_hc_prov_ty_3_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/185-sp_nrt_d_move_state_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/190-sp_nrt_d_out_of_cntry_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/195-sp_nrt_d_moved_where_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/200-sp_nrt_d_smr_exam_ty_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/215-sp_nrt_d_var_pam_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/225_sp_nrt_d_rash_loc_gen_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/230-sp_nrt_d_pcr_source_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/235-sp_nrt_var_pam_ldf_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/250-sp_var_datamart_postprocessing-001.sql

This ticket includes handling updates/deletes for TB/VAR. The outstanding issue with handling F_TB_PAM and F_VAR_PAM when there are any deletes to the dimension tables/ group tables is handled and fixed through this PR
- **Related story**: [CNDE-2563](https://cdc-nbs.atlassian.net/browse/CNDE-2563)

CNDE-2563 - TB & VAR - Handling updates/deletes

---

db/upgrade/odse/routines/006-sp_investigation_event.sql
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql

This ticket includes the code fix to address the gap in the investigation preprocessing for the confirmation method. 
- **Related story**: [CNDE-2583](https://cdc-nbs.atlassian.net/browse/CNDE-2583)

CNDE-2583 - Investigation Confirmation Date - Gap Fix

---

db/upgrade/rdb_modern/routines/295-sp_ldf_mumps_datamart_postprocessing.sql
db/upgrade/rdb_modern/tables/240-create_ldf_mumps.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/295-sp_ldf_mumps_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/240-create_ldf_mumps-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

This ticket includes post-processing changes for LDF_MUMPS. 
- **Related story**: [CNDE-2495](https://cdc-nbs.atlassian.net/browse/CNDE-2495)

CNDE-2495 Post Processing for LDF_MUMPS

---

db/upgrade/rdb_modern/routines/041-sp_pertussis_case_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/043-sp_pertussis_case_datamart_postprocessing-001.sql

SAS to SQL: Resolve data Inconsistency for `PERTUSSIS_TREATMENT_FIELD` and `PERTUSSIS_SUSPECTED_SOURCE_FLD`
- **Related story**: [CNDE-2593](https://cdc-nbs.atlassian.net/browse/CNDE-2593)

CNDE-2593: Pertussis Case fact tables data inconsistency

---

db/upgrade/odse/routines/022-sp_vaccination_event.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
liquibase-service/src/main/resources/db/odse/routines/027-sp_vaccination_event-001.sql

- **Related story**: [CNDE-2508](https://cdc-nbs.atlassian.net/browse/CNDE-2508)

CNDE-2508: Minor Fixes to Proc

---

db/upgrade/rdb_modern/routines/315-sp_covid_contact_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/315-sp_covid_contact_datamart_postprocessing-001.sql

updated the name of the procedure
- **Related story**: [CNDE-2524](https://cdc-nbs.atlassian.net/browse/CNDE-2524)

hotfix:updated the name

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java

A quick hot fix on java code to change the condition appropriately.
- **Related story**: [CNDE-2508](CNDE-2508)

CNDE-2508: hot fix

---

person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/PersonExtendedProps.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/persondetail/Name.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/transformer/DataPostProcessor.java
person-service/src/test/java/gov/cdc/etldatapipeline/person/PersonDataPostProcessingTests.java
person-service/src/test/java/gov/cdc/etldatapipeline/person/PersonDetailsDeserializationTests.java
person-service/src/test/resources/rawDataFiles/person/PersonName.json
person-service/src/test/resources/rawDataFiles/person/PersonName1.json
person-service/src/test/resources/rawDataFiles/person/ProviderName.json

When Person Service process the received data is not setting the right Name Suffix. It is getting the Suffix value from nmSuffix  from person instead of name_suffix from person_name
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2560)

CNDE-2560 Wrong suffix in D_PATIENT

---

db/upgrade/odse/routines/022-sp_vaccination_event.sql
db/upgrade/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing.sql
db/upgrade/rdb_modern/routines/310-sp_covid_case_datamart_postprocessing.sql
db/upgrade/rdb_modern/routines/320-sp_covid_vaccination_datamart_postprocessing.sql
db/upgrade/rdb_modern/tables/051-create_nrt_vaccination.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Vaccination.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/VaccinationReporting.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/utils/TestUtils.java
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/routines/027-sp_vaccination_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/130-sp_dyn_dm_case_management_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/310-sp_covid_case_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/320-sp_covid_vaccination_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/051-create_nrt_vaccination-001.sql

This change includes 
-  covid_vaccination_datamart_postprocessing procedure
- minor change to preprocessing of vaccination to include a field
- minor change on covid_case_datamart_postprocessing.sql
- **Related story**: [CNDE-2526](https://cdc-nbs.atlassian.net/browse/CNDE-2526)

CNDE-2526: Covid Vac Datamart processing

---

db/upgrade/odse/functions/006-fn_get_value_to_pascal_case.sql
db/upgrade/odse/routines/006-sp_investigation_event.sql
db/upgrade/rdb_modern/routines/006-sp_s_pagebuilder_postprocessing.sql
liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
liquibase-service/src/main/resources/db/odse/routines/028-fn_get_value_to_pascal_case-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/007-sp_s_pagebuilder_postprocessing-001.sql

Fixes to address these columns in various datamarts.
- BIRTH_WEIGHT
- GESTATIONAL_AGE_WEEKS
- IMPORT_FRM_COUNTRY
- **Related story**: [CNDE-2573](https://cdc-nbs.atlassian.net/browse/CNDE-2573)

CNDE-2573: Bug fixes for DynMarts

---

investigation-service/build.gradle
ldfdata-service/build.gradle
liquibase-service/build.gradle
observation-service/build.gradle
organization-service/build.gradle
person-service/build.gradle
post-processing-service/build.gradle
status-service/build.gradle

Address the CVE vulnerabilities raised in the 7.9.3 release and patch

Address the CVE vulnerabilities raised in the 7.9.3 release and patch

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

This PR reduces multiple calls of LDF_VACCINE_PREVENT post-processing sp into one single call.
- **Related story**: [CNDE-2592](https://cdc-nbs.atlassian.net/browse/CNDE-2592)

CNDE-2592:  RTR Optimize LDF_VACCINE_PREVENT post-processing

---

db/upgrade/rdb_modern/routines/043-sp_inv_summary_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/045-sp_inv_summary_datamart_postprocessing-001.sql

The PR alters the flow for `sp_inv_summ_datamart_postprocessing` in order to account for deleted records. The deleted records must be returned to the postprocessing service so they can be deleted downstream in the dynamic datamarts as well.
- **Related story**: [CNDE-2701](https://cdc-nbs.atlassian.net/browse/CNDE-2701)

CNDE-2701: return deletes in INV_SUMM_DATAMART postprocessing

---

db/upgrade/rdb_modern/routines/325-sp_covid_lab_celr_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/325-sp_covid_lab_celr_datamart_postprocessing-001.sql

This PR includes a minor change to the procedure and a fix needed to changelog file.
- **Related story**: [CNDE-2574](https://cdc-nbs.atlassian.net/browse/CNDE-2574)

CNDE-2574: Minor changes to proc and fix to changelog

---

db/upgrade/rdb_modern/tables/019-create_nrt_datamart_metadata.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql

Update nrt_datamart_metadata's datamart column length to accept covid datamart names. 

Liquibase Hotfix: Update nrt_datamart_metadata length

---

db/upgrade/rdb_modern/routines/003-sp_nrt_patient_postprocessing.sql
db/upgrade/rdb_modern/routines/004-sp_nrt_investigation_postprocessing.sql
db/upgrade/rdb_modern/routines/005-sp_nrt_notification_postprocessing.sql
db/upgrade/rdb_modern/routines/015-sp_nrt_morbidity_report_postprocessing.sql
db/upgrade/rdb_modern/routines/016-sp_d_labtest_result_postprocessing.sql
db/upgrade/rdb_modern/routines/035-sp_d_contact_record_postprocessing.sql
db/upgrade/rdb_modern/routines/042-sp_d_vaccination_postprocessing.sql
db/upgrade/rdb_modern/routines/043-sp_inv_summary_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
liquibase-service/src/main/resources/db/rdb_modern/routines/004-sp_nrt_patient_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/016-sp_nrt_morbidity_report_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/017-sp_d_labtest_result_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/036-sp_d_contact_record_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/044-sp_d_vaccination_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/045-sp_inv_summary_datamart_postprocessing-001.sql

This PR updated post-processing stored procedures returning datamart metadata to support COVID datamarts integration.
- **Related story**: [CNDE-2710](https://cdc-nbs.atlassian.net/browse/CNDE-2710)

CNDE-2710: Stored Proc changes to support Covid DMs Integration

---

db/upgrade/odse/routines/021-sp_treatment_event.sql
liquibase-service/src/main/resources/db/odse/routines/026-sp_treatment_event-001.sql

sp_treatment_event is failing in NBS_ODSE due to an error in the stored procedure code. There is an extra column in a query reading a temporary table but that temporary table doesn't have that column "t.public_health_case_uid". 
This columns is not used in the java service and also there is not present in nrt_treatment
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2416)

CNDE-2416_Morbidity_Datamart_Treatment_related_columns_are_NULL

---

db/upgrade/rdb_modern/routines/014-sp_nrt_ldf_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/015-sp_nrt_ldf_postprocessing-001.sql

This ticket includes handling deletes in the ldf_data and related group tables. Also, the logic for the group tables to join using the business_object_id instead of ldf_uid for updates/inserts is corrected. The FK reference is also updated for the group tables to set to 1 when handling deletes
- **Related story**: [CNDE-2697](https://cdc-nbs.atlassian.net/browse/CNDE-2697)

CNDE-2697 Handling Deletes in LDF_DATA and Group tables

---

db/upgrade/rdb_modern/routines/006-sp_s_pagebuilder_postprocessing.sql
db/upgrade/rdb_modern/routines/008-sp_d_pagebuilder_postprocessing.sql
db/upgrade/rdb_modern/routines/009-sp_sld_investigation_repeat_postprocessing.sql
db/upgrade/rdb_modern/routines/010-sp_page_builder_postprocessing.sql
db/upgrade/rdb_modern/routines/034-sp_repeated_place_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/007-sp_s_pagebuilder_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/009-sp_d_pagebuilder_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/010-sp_sld_investigation_repeat_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/011-sp_page_builder_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/035-sp_repeated_place_postprocessing-001.sql

Fixes phc_id_list processing
- **Related story**: [CNDE-2702](https://cdc-nbs.atlassian.net/browse/CNDE-2702)

CNDE-2702: Hot fix for phc_id_list

---

db/upgrade/rdb_modern/routines/008-sp_d_pagebuilder_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/009-sp_d_pagebuilder_postprocessing-001.sql

Fixes STRING_SPLIT issue
- **Related story**: [CNDE-2702](https://cdc-nbs.atlassian.net/browse/CNDE-2702)

CNDE-2702: Hot fix for string_split

---

db/upgrade/rdb_modern/routines/310-sp_covid_case_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/310-sp_covid_case_datamart_postprocessing-001.sql

Fixing some issues in stored procedure and adding some improvements
Errors:
1- Field Confirmation_Method was returning all confirmations methods instead of the corresponding confirmation methods. Resolution: compute the correct corresponding confirmation methods
2- In the last insert, some fields were truncated rising errors. Resolution: Cast varchar fields according to the existing (at the insert moment) table fields.
3- The inserted rowcount in the final insert was not displayed in logs, always was “0”
Improvements:
1- Adding the received @phc_uidsto the Start step in stored procedure Logs 
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2816)

CNDE-2816 sp_covid_case_datamart_postprocessing

---

db/upgrade/rdb_modern/routines/330-sp_covid_lab_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/330-sp_covid_lab_datamart_postprocessing-001.sql

Update stored procedure to fix observation result and ordering/provider state name mapping. 
- **CNDE-2751**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2751)

CNDE-2751: Hotfix for Covid Lab Results

---

investigation-service/build.gradle
ldfdata-service/build.gradle
observation-service/build.gradle
organization-service/build.gradle
person-service/build.gradle
post-processing-service/build.gradle

CNDE-2855: Upgrade tomcat dependency in RTR services

CNDE-2855: Upgrade tomcat dependency in RTR services

---

common-util/build.gradle
common-util/src/test/java/gov/cdc/etldatapipeline/commonutil/CommonUtilApplicationTests.java
investigation-service/build.gradle
ldfdata-service/build.gradle
liquibase-service/build.gradle
observation-service/build.gradle
organization-service/build.gradle
person-service/build.gradle
post-processing-service/build.gradle
status-service/build.gradle

Upgrade SpringBoot framework version to 3.5.0 to address the RTR services cve vulnerabilities
- **Related story**: [CNDE-2855](https://cdc-nbs.atlassian.net/browse/CNDE-2855)

CNDE-2855: Upgrade Spring Boot to 3.5.0

---

db/upgrade/rdb_modern/routines/045-sp_nrt_treatment_postprocessing.sql
db/upgrade/rdb_modern/tables/042-create_nrt_treatment.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Treatment.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/TreatmentReportingKey.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/utils/TestUtils.java
liquibase-service/src/main/resources/db/rdb_modern/routines/047-sp_nrt_treatment_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/042-create_nrt_treatment-001.sql

This PR updates nrt_treatment UID columns types and from the varchar to the bigint data type. Related pre- and post-processing logic are reviewed and updated to ensure compatibility with the new bigint column types.
- **Related story**: [CNDE-2846](https://cdc-nbs.atlassian.net/browse/CNDE-2846)

CNDE-2846: Change treatment UID column types to bigint

---

db/upgrade/rdb_modern/tables/dts1-001-create_ldf_datamart_table_ref.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/dts1-001-create_ldf_datamart_table_ref-001.sql

This ticket includes adding a new CC for the BMIRD in the LDF_DATAMART_TABLE_REF for the INT1 testing purpose
- **Related story**: [CNDE-2493](https://cdc-nbs.atlassian.net/browse/CNDE-2493)

Added new CC for the INT1 environment

---

db/upgrade/rdb_modern/routines/315-sp_covid_contact_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/315-sp_covid_contact_datamart_postprocessing-001.sql

COVID_CONTACT_DAMART reworked to use reverse reference for code values from the descriptions.
- **Related story**: [CNDE-2852](https://cdc-nbs.atlassian.net/browse/CNDE-2852)

CNDE-2852: reworking COVID contact datamart logic

---

organization-service/src/main/java/gov/cdc/etldatapipeline/organization/service/OrganizationService.java
organization-service/src/main/resources/application.yaml
organization-service/src/test/java/gov/cdc/etldatapipeline/organization/OrganizationDataProcessTests.java
organization-service/src/test/java/gov/cdc/etldatapipeline/organization/service/OrganizationServiceTest.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/service/PersonService.java
person-service/src/main/resources/application.yaml
person-service/src/test/java/gov/cdc/etldatapipeline/person/service/PersonServiceTest.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java

This PR adds feature flags to control producing ElasticSearch topics.
- **Related story**: [CNDE-2866](https://cdc-nbs.atlassian.net/browse/CNDE-2866)

CNDE-2866: Feature Flags for the Elastic Search topics

---

db/upgrade/rdb_modern/routines/028-sp_alter_datamart_schema_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/029-sp_alter_datamart_schema_postprocessing-001.sql

Change to remove references to srte database information schema
- **Related story**: [CNDE-2837](https://cdc-nbs.atlassian.net/browse/CNDE-2837)

CNDE-2837: Remove reference to srte database

---

db/upgrade/rdb_modern/routines/265-sp_nrt_ldf_dimensional_data_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/265-sp_nrt_ldf_dimensional_data_postprocessing-001.sql

All actions in stored procedure sp_nrt_ldf_dimensional_data_postprocessing over "LDF_DIMENSIONAL_DATA" table must take into account (ldf_uid, investigation_uid) 
add, update and delete actions over LDF_DIMENSIONAL_DATA table have been modified 
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2907)

CNDE-2907 Fixing bug in stored procedure sp_nrt_ldf_dimensional_data_postprocessing

---

db/upgrade/rdb_modern/routines/014-sp_nrt_ldf_postprocessing.sql
db/upgrade/rdb_modern/tables/226-create_ldf_data.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/015-sp_nrt_ldf_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/226-create_ldf_data-001.sql

Missing "CDC_CDC_NATIONAL_ID" when saving and updating LDF_DATA
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2912)

CNDE-2912 Missing "CDC_CDC_NATIONAL_ID" when saving and updating LDF_DATA in sp_nrt_ldf_postprocessing

---

liquibase-service/src/main/resources/db/rdb_modern/tables/028-create_nrt_srte_Condition_code-001.sql

Hotfix to address sink issue for nrt_srte_condition_code restored from rdb and not created via Liquibase.

Hotfix: Add rhapsody columns to Condition Code 

---

db/upgrade/rdb_modern/tables/220-create_nrt_srte_Treatment_code.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/220-create_nrt_srte_Treatment_code-001.sql

Fix to accomodate 6.0.17 updates to NBS_SRTE treatment_code's dose_qty_unit_cd
- **CNDE-2380**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2380)

CNDE-2380: 6.0.17 updates to srte treatment_code

---

db/upgrade/master/routines/008-create_kafka_sync_connector_service_user.sql

Added read permission for kafka sync
- **Related story**: [CNDE-2581](https://cdc-nbs.atlassian.net/browse/CNDE-2581)

Added read permission for kafka sync

---

db/upgrade/rdb_modern/routines/033-sp_case_lab_datamart_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/034-sp_case_lab_datamart_postprocessing-001.sql

Disease, Disease_CD Are computed from V_Condition_dim view and this view is deprecated. Code modified to use condition table
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2993)

[CNDE-2993] RTR - CASE_LAB_DATAMART table . Disease, Disease_CD mismatch

---

db/upgrade/odse/routines/020-sp_contact_record_event.sql
liquibase-service/src/main/resources/db/odse/routines/025-sp_contact_record_event-001.sql

Fix for certain CTT fields in D_CONTACT_RECORDS
- **Related story**: [CNDE-2971](https://cdc-nbs.atlassian.net/browse/CNDE-2971)

CNDE-2971: Fix for CONTACT RECORDS

---

investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/controller/InvestigationControllerTest.java
ldfdata-service/src/test/java/gov/cdc/etldatapipeline/ldfdata/config/KafkaConsumerConfigTest.java
ldfdata-service/src/test/java/gov/cdc/etldatapipeline/ldfdata/config/KafkaProducerConfigTest.java
liquibase-service/src/test/java/gov/cdc/etldatapipeline/controller/DataPipelineControllerTest.java
organization-service/src/test/java/gov/cdc/etldatapipeline/organization/OrganizationDataProcessTests.java
organization-service/src/test/java/gov/cdc/etldatapipeline/organization/controller/OrganizationServiceControllerTest.java
person-service/src/test/java/gov/cdc/etldatapipeline/person/controller/PersonServiceControllerTests.java
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java

This PR fixes issue for the following PostProcRepository method signatures:
- executeStoredProcForOrganizationIds
- executeStoredProcForProviderIds

CNDE-3014: Fix PostProcRepository repository

---

db/upgrade/rdb_modern/routines/014-sp_nrt_ldf_postprocessing.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/015-sp_nrt_ldf_postprocessing-001.sql
post-processing-service/src/main/resources/application.yaml

Fixing NRT records validation in the `sp_nrt_ldf_postprocessing`.
- **Related story**: [CNDE-3014](https://cdc-nbs.atlassian.net/browse/CNDE-3014)

CNDE-3014: Fix missing NRT record check in LDF post-processing sp

---

db/upgrade/odse/routines/016-sp_interview_event.sql
db/upgrade/odse/routines/020-sp_contact_record_event.sql
db/upgrade/odse/routines/022-sp_vaccination_event.sql
db/upgrade/rdb_modern/routines/022-sp_d_interview_postprocessing.sql
db/upgrade/rdb_modern/routines/035-sp_d_contact_record_postprocessing.sql
db/upgrade/rdb_modern/routines/042-sp_d_vaccination_postprocessing.sql
db/upgrade/rdb_modern/tables/022-create_nrt_metadata_columns.sql
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/MetadataColumn.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
liquibase-service/src/main/resources/db/odse/routines/021-sp_interview_event-001.sql
liquibase-service/src/main/resources/db/odse/routines/025-sp_contact_record_event-001.sql
liquibase-service/src/main/resources/db/odse/routines/027-sp_vaccination_event-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/023-sp_d_interview_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/036-sp_d_contact_record_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/routines/044-sp_d_vaccination_postprocessing-001.sql
liquibase-service/src/main/resources/db/rdb_modern/tables/022-create_nrt_metadata_columns-001.sql

Moving the need for flag column and encapsulating the queries in a single transaction.
- **Related story**: [CNDE-2971](url)

CNDE-2971: Fix for metadata columns

---

db/upgrade/odse/routines/002-sp_provider_event.sql
liquibase-service/src/main/resources/db/odse/routines/006-sp_provider_event-001.sql

Fix for PROVIDER_COUNTRY being null when it is 'US'.
- **Related story**: [CNDE-3037](https://cdc-nbs.atlassian.net/browse/CNDE-3037)

CNDE-3037: Fix for provider country

---

person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/patient/PatientReporting.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/patient/PatientSp.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/model/dto/persondetail/Name.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/transformer/PersonTransformers.java

Added the data compare tool difference fixes for D_Provider at PROVIDER_NAME_PREFIX and PATIENT_BIRTH_SEX
- **Related story**: 
[CNDE-2947](https://cdc-nbs.atlassian.net/browse/CNDE-2947)
[CNDE-2965](https://cdc-nbs.atlassian.net/browse/CNDE-2965)

[CNDE-2947] [CNDE-2965] - D_Provider - PROVIDER_NAME_PREFIX and PATIENT_BIRTH_SEX Fix for Data Compare Tool

---

liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Update file number for nrt_odse_lookup_question in rdb_modern changelog

Hotfix: Update file number in changelog

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/017-sp_d_labtest_result_postprocessing-001.sql

This fixes certain transactional failure issues that could happen within the stored procedure.
- **Related story**: [CNDE-3021](https://cdc-nbs.atlassian.net/browse/CNDE-3021)

CNDE-3021: update to transaction wrapping in lab_test_result sp

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/013-sp_hepatitis_datamart_postprocessing-001.sql

This PR removes an extra return value from `sp_hepatitis_datamart_postprocessing`.

Hotifx: remove extra return value from hepatitis_datamart

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql

Fix for `sp_nrt_notification_postprocessing`: add LDF datamart info into returned Datamart metadata.
- **Related story**: Hot Fix

HotFix: include LDF Datamart info into notification processing return

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/250-sp_var_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml

Liquibase rdb_modern changelog fix and var_datamart logic update to match confirmation method key. 

rdb_modern changelog fix and var_datamart logic update

---

liquibase-service/src/main/resources/db/005-rdb_modern/tables/251-create_nrt_lab_test_result_group_key-001.sql

Remove key value 1 for nrt_lab_test_result_group_key

Remove key value 1 for nrt_lab_test_result_group_key

---

post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java

Updating RTR post-processing service to accept datamart information from provider/organization post-processing workflow when it's available.
- **Related story**: [CNDE-3065](https://cdc-nbs.atlassian.net/browse/CNDE-3065)

CNDE-3065: Handling datamart metadata returned by provider and organization

---

liquibase-service/src/main/resources/db/005-rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql

nrt_datamart_metadata: Covid Datamart Update

---

liquibase-service/src/main/resources/db/005-rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql
post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceEntityTest.java

LDF_DATA: Update LDF_DIMENSIONAL_DATA after a new investigation is created.

LDF_DATA: Update LDF_DIMENSIONAL_DATA in postprocessing

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/185-sp_nrt_d_move_state_postprocessing-001.sql

Update reference from CODE_SHORT_DESC_TXT to CODE_DESC_TXT to align with classic ETL.
Updated:
- **CNDE-2991**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2991)

CNDE-2991: Fix for D_MOVE_STATE state value

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/004-sp_nrt_patient_postprocessing-001.sql
liquibase-service/src/main/resources/db/005-rdb_modern/routines/365-sp_patient_dim_columns_update_to_datamart.sql
liquibase-service/src/main/resources/db/005-rdb_modern/routines/370-sp_provider_dim_columns_update_to_datamart.sql

This PR is to change the strategy that is used to pick appropriate rows from the datamart for updating. Instead of using PAGE_CASE or STD_PAGE_CASE fact we will be using specific FACT tables like MORBIDITY_REPORT_EVENT, etc (if available) to make specific updates.
- **Related story**: [CNDE-3071](url)

CNDE-3071: Update the logic used to accurately update changed Provider and Patient data

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/028-sp_nrt_place_postprocessing-001.sql

`D_INV_PLACE_REPEAT` updates when an investigation event is received. Update `D_INV_PLACE_REPEAT` dimension on independent Place cdc event. 
`D_PLACE's` `PLACE_LOCATOR_UID` can be mapped to either `PLACE_AS_SEX_OF_PHC` or `PLACE_HANGOUT_OF_PHC` in `D_INV_PLACE_REPEAT`. 
Misalignment (left) D_INV_PLACE_REPEAT column, expected value (right) D_PLACE column
Update all D_INV_PLACE_REPEAT fields mapped to D_PLACE.
- **CNDE-2232**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2232)

Update D_INV_PLACE_REPEAT dimension in Place sproc

---

liquibase-service/src/main/resources/db/005-rdb_modern/routines/039-sp_hepatitis_case_datamart_postprocessing-001.sql
liquibase-service/src/main/resources/db/005-rdb_modern/routines/205-sp_dyn_dm_repeatvarch_postprocessing-001.sql
liquibase-service/src/main/resources/db/005-rdb_modern/routines/210-sp_dyn_dm_repeatdate_postprocessing-001.sql
liquibase-service/src/main/resources/db/005-rdb_modern/routines/235-sp_dyn_dm_repeatnumeric_postprocessing-001.sql

- Remove rogue print statements that add a few batches of records into the nrt_backfill table.
- Minor reformatting. 
- **Related story**: [CNDE-2463](https://cdc-nbs.atlassian.net/browse/CNDE-2463)

Remove print statements for retry logs

---

investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/InvestigationRepository.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
investigation-service/src/main/resources/application.yaml
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
liquibase-service/src/main/resources/db/003-odse/routines/030-sp_public_health_case_fact_datamart_update-001.sql
liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
organization-service/src/main/java/gov/cdc/etldatapipeline/organization/repository/OrgRepository.java
organization-service/src/main/java/gov/cdc/etldatapipeline/organization/service/OrganizationService.java
organization-service/src/test/java/gov/cdc/etldatapipeline/organization/service/OrganizationServiceTest.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/repository/PatientRepository.java
person-service/src/main/java/gov/cdc/etldatapipeline/person/service/PersonService.java
person-service/src/test/java/gov/cdc/etldatapipeline/person/service/PersonServiceTest.java

Integrating `PHCF` datamart selective updates into `Notification`, `Patient`, `Provider `and `Organization` data pre-processing.
- **Related story**: [CNDE-1743](https://cdc-nbs.atlassian.net/browse/CNDE-1743), [CNDE-1751](https://cdc-nbs.atlassian.net/browse/CNDE-1751)

CNDE-1743: PHCF datamart selective updates

---

liquibase-service/src/main/resources/db/001-master/02_onboarding_script_data_load/002-nrt_lab_rpt_user_comment_key-001.sql
liquibase-service/src/main/resources/db/001-master/02_onboarding_script_data_load/012-nrt_notification_key-001.sql

- **Related story**: [CNDE-3149](url)

CNDE-3149: Added safety net for nrt key loading scripts

---

liquibase-service/src/main/resources/db/001-master/01_onboarding_scripts_user_creation/000-create_rtr_admin_user-001.sql

- **Related story**: [CNDE-3151](url)

CNDE-3151: explicit permissions for sysjobs
