CDCgov/NEDSS-DataReporting

- liquibase-service/src/main/resources/db/odse/001-fn_get_value_by_cd_ques-001.sql
- liquibase-service/src/main/resources/db/odse/005-sp_organization_event-001.sql
- liquibase-service/src/main/resources/db/odse/006-sp_provider_event-001.sql
- liquibase-service/src/main/resources/db/odse/008-sp_patient_event-001.sql
- liquibase-service/src/main/resources/db/odse/010-sp_investigation_event-001.sql
- liquibase-service/src/main/resources/db/rdb/020-sp_nrt_organization_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/021-sp_nrt_provider_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/022-sp_nrt_patient_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/023-sp_nrt_investigation_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/024-sp_nrt_notification_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/030-sp_f_page_case_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/031-sp_hepatitis_datamart_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb/032-create_nrt_datamart_metadata-001.sql
Updates to stored procedures:
+ Including bug fix versions for ODSE pre-processing sprocs- trim/substring handling for address fields.
+ Updates hepatitis stored procedure to pull page builder inv dimensions columns that were being missed.
+ Addition of `with (nolock)` to table joins for multiple/heavy transaction handling. 
+ Correct sproc for investigation pre-processing.
> Liquibase: sproc updates with bug fixes

- common-util/src/main/java/gov/cdc/etldatapipeline/commonutil/NoDataException.java
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/service/ObservationService.java
- observation-service/src/test/java/gov/cdc/etldatapipeline/observation/service/ObservationServiceTest.java
- organization-service/src/main/java/gov/cdc/etldatapipeline/organization/service/OrganizationService.java
- organization-service/src/test/java/gov/cdc/etldatapipeline/organization/service/OrganizationServiceTest.java
- person-service/src/main/java/gov/cdc/etldatapipeline/person/service/PersonService.java
- person-service/src/test/java/gov/cdc/etldatapipeline/person/PersonServiceTest.java
Implement and throw a custom exception when the requested database object is unavailable on the database side (sp returns empty data for the specified uid). Send incoming message to DLT if empty data is returned from database.
- **NoDataException.java**: custom exception class;
- **Investigation**, **Observation**, **Organization**, **Person** services now throw the NoDataException in the `processMessage` listeners;
- Same logic is to be implemented in the context of upcoming **PostProcessing** and **LDF** services enhancement.
[CNDIT-1554](https://cdc-nbs.atlassian.net/browse/CNDIT-1554)
> CNDIT-1554: Send message to DLQ for empty or not existed database objects

- ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/model/dto/LdfDataKey.java
- ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/service/LdfDataService.java
- ldfdata-service/src/test/java/gov/cdc/etldatapipeline/ldfdata/service/LdfDataServiceTest.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/PostProcRepository.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/main/resources/application.yaml
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
Implements LDF service integration in RTR post-processing service to call `sp_nrt_ldf_postprocessing` and update LDF dimensions.
- `LdfDataKey.java`: removed `business_object_uid` field from the message key
- `PostProcRepository.java`: added method to execute `sp_nrt_ldf_postprocessing`
- `PostProcessingService.java`: added `nrt_ldf_data` topic processing, minor improvements
- Adjusted unit tests
[CNDIT-1364](https://cdc-nbs.atlassian.net/browse/CNDIT-1364)
> CNDIT-1364: LDF post-processing service integration

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
- investigation-service/src/main/resources/application.yaml
- liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
- Add a feature flag to the investigation service for PHC datamart processing. Can be enabled/disabled by by setting the `PHC_DM_ENABLE` environment variable. If the variable is not set, the default value is `false` and feature will be turned off.
- Fix investigation update sp for the investigations without notifications
> RTR investigation service - add PHC datamart feature flag

- liquibase-service/src/main/resources/db/odse/routines/009-sp_observation_event-001.sql
Update stored procedure procedure to call missing columns ctrl_cd_display_form, processing_decision_cd, cd and shared_ind.
> Liquibase Fix: Add missing Observation columns

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/config/KafkaConsumerConfig.java
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
- investigation-service/src/main/resources/application.yaml
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
- organization-service/src/main/java/gov/cdc/etldatapipeline/organization/transformer/DataPostProcessor.java
- person-service/src/main/java/gov/cdc/etldatapipeline/person/transformer/DataPostProcessor.java
Fixes Investigation service multiple processing of the same case when relatively large volume of investigations is updated instantly.
- **Application.yaml**: set `auto-commit-enable` to **false** and `max.poll.interval.ms` to 300000 (default value);
- **InvestigationService.java**: `add consumer.commitSync()` to manually commit offsets returned on the last poll.
[CNDIT-1702](https://cdc-nbs.atlassian.net/browse/CNDIT-1702)
> CNDIT-1702: RTR performance investigate and fix for investigation service topic duplication

- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
Address and fix the inconsistency in message processing order to ensure that `Investigation` messages are processed before their corresponding `Notification` messages, preventing its out-of-sequence processing.
[CNDIT-1761](https://cdc-nbs.atlassian.net/browse/CNDIT-1761)
> CNDIT-1761: Fix IDs processing order issue for RTR post-processing

- liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
- liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-001.sql
- liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-002.sql
- Fix for page builder multi-select with OTH specification: Join with SRTE code_value_general to query on the correct investigation form code. 
- Removal of session table for runtime improvement: [Notes](https://cdc-nbs.atlassian.net/wiki/x/AwAGO)
- Fix for NBS_Act_Entity grouping: Min for add time, max for last_chg_time to avoid pulling all entity records.
[CNDIT-1597](https://cdc-nbs.atlassian.net/browse/CNDIT-1597)
[CNDIT-1618](https://cdc-nbs.atlassian.net/browse/CNDIT-1618)
> CNDIT 1597+1618: Investigation stored procedure update for PB multi-select

- common-util/src/main/java/gov/cdc/etldatapipeline/commonutil/json/CustomJsonGeneratorImpl.java
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InvestigationNotification.java
Fix `schema` for `nrt_investigation_notification` payload to set `optional: fale` for `notification_uid`
> RTR Notification: Make notification_uid not optional in Kafka message schema

- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationNumeric.java
- observation-service/src/test/java/gov/cdc/etldatapipeline/observation/ObservationDataProcessTests.java
Fixed Java type for `ovn_numeric_value_1` and `ovn_numeric_value_2` to avoid Kafka sink DataException
- **Related story**: [CNDE-1777](https://cdc-nbs.atlassian.net/browse/CNDE-1777)
> CNDIT-1777 Fix ObservationNumeric data type for Kafka schema

- liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
- liquibase-service/src/main/resources/db/odse/routines/008-sp_patient_event-002.sql
DTS1_HEP datamart_PAT_BIRTH_COUNTRY is null when user selects certain countries on the patient tab within the Investigation (NBS UI). 
The `COUNTRY_CODE` tables doesn't have all the codes and hence nrt_patient populates it as null. The sp has been modified to use `CODE_VALUE_GENERAL` table
- **Related story**: [CNDE-1724](https://cdc-nbs.atlassian.net/browse/CNDE-1724)
> CNDE-1724: Fix for PAT_BIRTH_COUNTRY being null

- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationCodedKey.java
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationReasonKey.java
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationTxtKey.java
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/util/ProcessObservationDataUtil.java
Fixed the issue with persistence of multivalued data for `nrt_observation_coded`, `nrt_observation_reason` and `nrt_observation_txt`.
- **Related story**: [CNDE-1834](https://cdc-nbs.atlassian.net/browse/CNDE-1834)
> CNDE-1834: Fix persistence for multivalued observation payloads

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Investigation.java
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InvestigationReporting.java
- liquibase-service/src/main/resources/db/changelog/db.odse.changelog-16.1.yaml
- liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
- liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-002.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-002.sql
Removing redundant notification fields from the Investigation DTOs `nrt_investigation` and `sp_investigation_event`.
- `notification_uid` (sp only)
- `notification_local_id`
- `notification_add_time`
- `notification_record_status_cd`
- `notification_last_chg_time`
- **Related story**: [CNDE-1802](https://cdc-nbs.atlassian.net/browse/CNDE-1802)
> CNDE-1802: RTR remove redundant fields from the Investigation

- liquibase-service/src/main/resources/db/rdb_modern/routines/017-sp_d_labtest_result_postprocessing-002.sql
Fix for `LAB100` datamart - lab test result comment update/delete.
- `UPDATE LAB_TEST_RESULT` query fixed
- `LAB_RESULT_COMMENT` and `RESULT_COMMENT_GROUP` records deleted if comment is deleted
- **Related story**: [CNDE-1942](https://cdc-nbs.atlassian.net/browse/CNDE-1942)
> CNDE-1942: LAB100 Result Comment Hydration

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Investigation.java
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/InvestigationReporting.java
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
- liquibase-service/src/main/resources/db/changelog/db.rdb_modern.changelog-16.1.yaml
- liquibase-service/src/main/resources/db/odse/routines/009-sp_observation_event-003.sql
- liquibase-service/src/main/resources/db/odse/routines/010-sp_investigation_event-002.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-003.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/007-create_nrt_investigation-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_date-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation_numeric-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/views/002-v_getobsdate-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/views/003-v_getobsnum-001.sql
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationDate.java
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/repository/model/reporting/ObservationNumeric.java
- observation-service/src/test/java/gov/cdc/etldatapipeline/observation/ObservationDataProcessTests.java
- observation-service/src/test/resources/rawDataFiles/ObservationDate.json
- observation-service/src/test/resources/rawDataFiles/ObservationNumeric.json
Updates to align data between baseline and RTR Investigation dimension. 
- Correct assignment of INV_ASSIGNED DATE for legacy investigations. 
- Additional seq column for views  for legacy investigations. 
- Assign NULL to empty strings. 
- Update nrt_investigation to get outbreak_name_desc.
- Bug fix for order_facility_uid in sp_investigation_event. 
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-1916?atlOrigin=eyJpIjoiNjc4YjMxZmVhODEzNDg3Yzg2NzM4OGM2ZTBjZjUzMzkiLCJwIjoiaiJ9)
> CNDE-1916: Align RTR Investigation with baseline

- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/ProcessDatamartData.java
Move Hepatitis Datamart Post-Processing to end of chain.
- Relocated the post-processing method for generating the Hepatitis datamart topic to the end of the post-processing chain.
- Ensures all dependent data (patient, investigation, notification, lab) is processed before scheduling the datamart run.
- **Related story**: [CNDE-1951](https://cdc-nbs.atlassian.net/browse/CNDE-1951)
> CNDE-1951: Re-order Hepatitis datamart post-processing

- db/upgrade/rdb_modern/routines/031-sp_crs_case_datamart_postprocessing.sql
The column label is missing from #OBS_CODED_CRS_Case. This is causing the datamart modification proc to fail within CRS_Case. 
Fix: The column is already in the CTE used to create the temp table, but needs to be referenced in the actual select statement as well.
- **Related story**: [CNDE-2220](https://cdc-nbs.atlassian.net/browse/CNDE-2220)
> CNDE-2220: Add label column to coded temp table (Bugfix)

- common-util/src/main/java/gov/cdc/etldatapipeline/commonutil/UtilHelper.java
- db/upgrade/rdb_modern/tables/019-create_nrt_datamart_metadata.sql
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
- investigation-service/src/main/resources/application.yaml
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
- liquibase-service/src/main/resources/db/rdb_modern/tables/019-create_nrt_datamart_metadata-001.sql
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/Entity.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/ProcessDatamartData.java
- post-processing-service/src/main/resources/application.yaml
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/DatamartProcessingTest.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
- post-processing-service/src/test/resources/rawDataFiles/BMIRDCaseDatamart.json
Adds feature flags for enabling `BMIRD`, `Contact Record` in pre-processing and for `Event Metric` in the post-processing service. Default value is `OFF`. Helm charts will manage the actual flag values for each environment.
A feature flag for `Treatment` will be added when its implementation begins.
- **Related story**: [CNDE-2253](https://cdc-nbs.atlassian.net/browse/CNDE-2253)
> CNDE-2253: Add feature flags for BMIRD, Contact Record and Event Metric

- liquibase-service/src/main/resources/db/rdb_modern/routines/002-sp_nrt_organization_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/003-sp_nrt_provider_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/004-sp_nrt_patient_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/005-sp_nrt_investigation_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/015-sp_nrt_ldf_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/022-sp_nrt_case_management_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/028-sp_nrt_place_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/034-sp_case_lab_datamart_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/035-sp_repeated_place_postprocessing-001.sql
Some post processing stored procedures were incorrectly returning the `@ErrorMessage` variable upon error, when they should have been returning `-1`. This PR contains the fix for that.
- **Related story**: [CNDE-2278](https://cdc-nbs.atlassian.net/browse/CNDE-2278)
> CNDE-2278: fix return statements in postprocessing

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/util/ProcessInvestigationDataUtil.java
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/InvestigationDataProcessingTests.java
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
Adds .whenComplete listener and logs to tombstone messages to initialize subsequent inserts only when deleting message accepted by consumer.
- **Related story**: [CNDE-2277](https://cdc-nbs.atlassian.net/browse/CNDE-2277)
> CNDE-2277 Refactor Kafka tombstone messages to prevent deadlocks

- db/upgrade/rdb_modern/routines/039-sp_bmird_case_datamart_postprocessing.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/040-sp_bmird_case_datamart_postprocessing-001.sql
This PR fixes insert/update statements to avoid including the BMD124 column twice.
- **Related story**: [CNDE-2254](https://cdc-nbs.atlassian.net/browse/CNDE-2254)
> CNDE-2254: Quick fix for BMD124 insert

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/reporting/PageCaseAnswer.java
Hotfix to set nbsRdbMetadataUid to null for Page case answers to accommodate INV data.
- **Related story**: [CNDE-2334](https://cdc-nbs.atlassian.net/browse/CNDE-2334)
> CNDE-2334 hotfix for setting nbsRdbMetadataUid to null

- db/upgrade/odse/routines/005-sp_observation_event.sql
- db/upgrade/rdb_modern/routines/220-sp_nrt_tb_pam_ldf_postprocessing.sql
- db/upgrade/rdb_modern/tables/017-create_nrt_observation.sql
- liquibase-service/src/main/resources/db/odse/routines/009-sp_observation_event-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/220-sp_nrt_tb_pam_ldf_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/017-create_nrt_observation-001.sql
This PR makes the necessary updates to `sp_observation_event`, `nrt_observation`, and the Observation Java service for including a comma separated list of phc_uids that are associated with a given observation.
- **Related story**: [CNDE-2511](https://cdc-nbs.atlassian.net/browse/CNDE-2511)
> CNDE-2511: add phc_uids to nrt_observation

- db/upgrade/odse/routines/021-sp_treatment_event.sql
- db/upgrade/rdb_modern/tables/042-create_nrt_treatment.sql
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/repository/model/dto/Treatment.java
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/utils/TestUtils.java
- liquibase-service/src/main/resources/db/odse/routines/026-sp_treatment_event-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/042-create_nrt_treatment-001.sql
Adds `associated_phc_uids` column to `dbo.nrt_treatment` and updates the stored procedure and service to populate it.
NOTE: For the time being, the `public_health_case_uid` column is being left in. This is to prevent Liquibase from failing when trying to run the script for the treatment postprocessing stored procedure. In the next PR for updating that procedure, I'll remove the column from the nrt table, event stored procedure, and Treatment.java class.
- **Related story**: [CNDE-2512](https://cdc-nbs.atlassian.net/browse/CNDE-2512)
> CNDE-2512: add associated_phc_uids to Treatment

- db/upgrade/rdb_modern/routines/006-sp_s_pagebuilder_postprocessing.sql
- db/upgrade/rdb_modern/routines/009-sp_sld_investigation_repeat_postprocessing.sql
- db/upgrade/rdb_modern/routines/011-sp_f_page_case_postprocessing.sql
- db/upgrade/rdb_modern/routines/015-sp_nrt_morbidity_report_postprocessing.sql
- db/upgrade/rdb_modern/routines/017-sp_d_lab_test_postprocessing.sql
- db/upgrade/rdb_modern/routines/018-sp_lab100_datamart_postprocessing.sql
- db/upgrade/rdb_modern/routines/024-sp_f_std_page_case_postprocessing.sql
- db/upgrade/rdb_modern/routines/031-sp_crs_case_datamart_postprocessing.sql
- db/upgrade/rdb_modern/routines/046-sp_morbidity_report_datamart_postprocessing.sql
- db/upgrade/rdb_modern/views/001-v_getobscode.sql
- db/upgrade/rdb_modern/views/013-v_rdb_obs_mapping.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/007-sp_s_pagebuilder_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/010-sp_sld_investigation_repeat_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/012-sp_f_page_case_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/016-sp_nrt_morbidity_report_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/018-sp_d_lab_test_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/019-sp_lab100_datamart_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/025-sp_f_std_page_case_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/032-sp_crs_case_datamart_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/048-sp_morbidity_report_datamart_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/views/001-v_getobscode-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/views/013-v_rdb_obs_mapping-001.sql
DB performance optimization. All the references to `NBS_SRTE` database in post-processing stored procedures and views are replaced with references to the `nrt_srte` replica tables.
- **Related story**: [CNDE-2381](https://cdc-nbs.atlassian.net/browse/CNDE-2381)
> CNDE-2381: Replace SRTE db references within stored procedures to nrt_srte

- db/upgrade/rdb_modern/routines/015-sp_nrt_morbidity_report_postprocessing.sql
- db/upgrade/rdb_modern/routines/046-sp_morbidity_report_datamart_postprocessing.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/016-sp_nrt_morbidity_report_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/048-sp_morbidity_report_datamart_postprocessing-001.sql
This PR includes the necessary changes to properly populate the investigation keys in `dbo.MORBIDITY_REPORT_EVENT` as well as `dbo.MORBIDITY_REPORT_DATAMART` .
- **Related story**: [CNDE-2509](https://cdc-nbs.atlassian.net/browse/CNDE-2509)
> CNDE-2509: Fix investigation_key associations in Morbidity Reports

- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/ProcessDatamartData.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceTest.java
This ticket includes fix for handling empty Datamart values and preventing datamart processing loop
- **Related story**: [CNDE-2565](https://cdc-nbs.atlassian.net/browse/CNDE-2565)
> CNDE-2565 Process Empty DM in Java post processing

- db/upgrade/rdb_modern/routines/005-sp_nrt_notification_postprocessing.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/006-sp_nrt_notification_postprocessing-001.sql
This ticket includes handling Empty Datamart values. Currently, the sp_nrt_notification_postprocessing  has a left join to the  nrt_datamart_metadata. This is changed to Inner Join. 
No changes required in:
sp_d_morbidity_report_postprocessing
sp_d_labtest_result_postprocessing
- **Related story**: [CNDE-2568](https://cdc-nbs.atlassian.net/browse/CNDE-2568)
> CNDE-2568 Handling Empty Datamart Names in Postprocessing

- db/upgrade/odse/routines/004-sp_patient_event.sql
- liquibase-service/src/main/resources/db/odse/routines/008-sp_patient_event-001.sql
Country text was taken from nbs_srte.dbo.CODE_VALUE_GENERAL where the country name is in Capital letters. Also it requires rank. Nevertheless if we take the country name from  nbs_srte.dbo.Country_CODE , the country name is not in Capital letters and it doesn't require rank
Also, Birth_country must be read from nbs_srte.dbo.CODE_VALUE_GENERAL. So
- **Related story**: [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNDE-2361)
> CNDE-2361 D_PATIENT patient country populating incorrectly

- common-util/src/main/java/gov/cdc/etldatapipeline/commonutil/UtilHelper.java
- common-util/src/test/java/gov/cdc/etldatapipeline/commonutil/UtilHelperTest.java
- ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/service/LdfDataService.java
- ldfdata-service/src/test/java/gov/cdc/etldatapipeline/ldfdata/service/LdfDataServiceTest.java
This PR refactors the utility method responsible for extracting UIDs from Kafka message payloads, particularly to support Debezium messages generated with **snapshot.mode=initial**, which may lack child nodes like `after` or `before`.
- UitlHelper::extractUid - updated to handle UID extraction from payloads with or without an `after` node.
- LdfDataService - revised its custom extractUid method to align with the new logic.
- **Related story**: [CNDE-2809](https://cdc-nbs.atlassian.net/browse/CNDE-2809)
> CNDE-2809: Refactor extractUid for NBS_ODSE snapshots

- ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/model/dto/LdfDataKey.java
- ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/service/LdfDataService.java
- ldfdata-service/src/test/java/gov/cdc/etldatapipeline/ldfdata/service/LdfDataServiceTest.java
This ticket includes the bug fix for setting business_obj_uid as PK along with LDF_UID to eliminate overriding of the values in nrt_ldf_data
- **Related story**: [CNDE-2903](https://cdc-nbs.atlassian.net/browse/CNDE-2903)
> CNDE-2903 LDF_Service doesnt contain Business_object_uid as PK

- db/upgrade/rdb_modern/tables/211-create_nrt_srte_Snomed_condition.sql
- liquibase-service/src/main/resources/db/rdb_modern/tables/211-create_nrt_srte_Snomed_condition-001.sql
- Handle table (snomed_condition) with no primary key in source table. 
- Update target sink table to contain primary key. 
Sample debezium config :
```
table.include.list= dbo.Snomed_condition
tasks.max=1
#topic.creation.default.replication.factor= 2,
#topic.creation.default.partitions= 10,
#topic.creation.default.cleanup.policy=compact
time.precision.mode= connect
transforms= dropPrefix, dropPrefixConfig, unwrapConfig, valueToKey, convertTimezone, unwrap, convertTimestamps_add_time, convertTimestamps_concept_status_time, convertTimestamps_effective_from_time, convertTimestamps_effective_to_time, convertTimestamps_status_time, convertTimestamps_status_to_time, convertTimestamps_value_set_status_time, convertTimestampsConfig_effective_from_time, convertTimestampsConfig_effective_to_time, …
```
> CNDE-2380: Fix for Kafka sink error on snomed_condition

- db/upgrade/rdb_modern/routines/245-sp_dyn_dm_createdm_postprocessing.sql
- db/upgrade/rdb_modern/routines/335-sp_nrt_odse_nbs_page_postprocessing.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/245-sp_dyn_dm_createdm_postprocessing-001.sql
- liquibase-service/src/main/resources/db/rdb_modern/routines/335-sp_nrt_odse_nbs_page_postprocessing-001.sql
This PR introduces changes to STRING_AGG in `sp_nrt_odse_nbs_page_postprocessing` and `sp_dyn_dm_createdm_postprocessing` that will prevent truncation/overflow errors when aggregating a large number of strings.
- **Related story**: [CNDE-2996](https://cdc-nbs.atlassian.net/browse/CNDE-2996)
> CNDE-2996: Address STRING_AGG overflow bug in Page Postprocessing

- liquibase-service/src/main/resources/db/001-master/02_onboarding_script_data_load/000-nrt_metadata_load-001.sql
- liquibase-service/src/main/resources/db/001-master/02_onboarding_script_data_load/1003-enable_cdc_on_srte_database-001.sql
- liquibase-service/src/main/resources/db/001-master/02_onboarding_script_data_load/999-reseed_nrt_key-001.sql
Scripts to bulk load Metadata tables from ODSE and SRTE database to the RTR Reporting database as an Onboarding effort.
These scripts are needed to avoid Debezium snapshot process taking longer to run and locking the tables.
- **Related story**: [Cnde 3050](https://cdc-nbs.atlassian.net/browse/CNDE-3050)
> Scripts to bulk load Metadata tables from ODSE and SRTE database to the RTR Reporting database as an Onboarding effort.

- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/repository/InvestigationRepository.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/ProcessDatamartData.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/DatamartProcessingTest.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceDmTest.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceEntityTest.java
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceRetryTest.java
Enhancing RTR post-processing by adding error handling for datamarts execution.
- The majority of datamart processing logic moved to `ProcessDatamartData` component
- Unit tests updated to cover datamarts retry and backfill processing
- **Related story**: [CNDE-3064](url)
> CNDE-3064: RTR post-processing refactor for Datamart retry mechanism

- .github/workflows/Build-and-deploy-reporting-services.yaml
CNDE-3094 : Update the github actions to deploy the latest image tags build from the main branch in the RTR Java services helm chart
> CNDE-3094 : Update the github actions to deploy the latest image tags build from the main branch in the RTR Java services helm chart

- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingService.java
- post-processing-service/src/main/resources/application.yaml
- post-processing-service/src/test/java/gov/cdc/etldatapipeline/postprocessingservice/service/PostProcessingServiceEntityTest.java
Introduces a feature flag to optionally skip processing of consumed nrt_ topic messages in the RTR Post-processing service.
- **Related story**: [CNDE-3136](https://cdc-nbs.atlassian.net/browse/CNDE-3136)
> CNDE-3136: Add feature flag to disable post-processing

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
- investigation-service/src/main/resources/application.yaml
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
- organization-service/src/main/java/gov/cdc/etldatapipeline/organization/service/OrganizationService.java
- organization-service/src/main/resources/application.yaml
- organization-service/src/test/java/gov/cdc/etldatapipeline/organization/service/OrganizationServiceTest.java
- person-service/src/main/java/gov/cdc/etldatapipeline/person/service/PersonService.java
- person-service/src/main/resources/application.yaml
- person-service/src/test/java/gov/cdc/etldatapipeline/person/service/PersonServiceTest.java
Introduces a feature to bypass PHCF stored procedure(s) execution. Applies to
- investigation-service
- organizrion-service
- person-service
- **Related story**: [CNDE-3138](https://cdc-nbs.atlassian.net/browse/CNDE-3138)
> CNDE-3138: Add feature flag to disable PHCF datamart

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/config/KafkaConsumerConfig.java
- investigation-service/src/main/resources/application.yaml
- ldfdata-service/src/main/java/gov/cdc/etldatapipeline/ldfdata/config/KafkaConsumerConfig.java
- ldfdata-service/src/main/resources/application.yaml
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/config/KafkaConsumerConfig.java
- observation-service/src/main/resources/application.yaml
- organization-service/src/main/java/gov/cdc/etldatapipeline/organization/config/KafkaConsumerConfig.java
- organization-service/src/main/resources/application.yaml
- person-service/src/main/java/gov/cdc/etldatapipeline/person/config/KafkaConsumerConfig.java
- person-service/src/main/resources/application.yaml
- post-processing-service/src/main/java/gov/cdc/etldatapipeline/postprocessingservice/config/KafkaConsumerConfig.java
Add the max.poll.records as a configurable parameter to the kafka consumer micro-services
> Add the max.poll.records as a configurable parameter to the kafka consumer micro-services

- organization-service/src/main/java/gov/cdc/etldatapipeline/organization/service/OrganizationService.java
- organization-service/src/main/resources/application.yaml
- organization-service/src/test/java/gov/cdc/etldatapipeline/organization/service/OrganizationServiceTest.java
Introduce a configurable thread pool for the RTR Organization pre-processing service to allow parallel execution of organization data processing tasks.
- **Related story**: [CNDE-3152](https://cdc-nbs.atlassian.net/browse/CNDE-3152)
> CNDE-3152: Configurable thread pool for OrganizationService

- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/config/KafkaConsumerConfig.java
- investigation-service/src/main/java/gov/cdc/etldatapipeline/investigation/service/InvestigationService.java
- investigation-service/src/test/java/gov/cdc/etldatapipeline/investigation/service/InvestigationServiceTest.java
- observation-service/src/main/java/gov/cdc/etldatapipeline/observation/config/KafkaConsumerConfig.java
- organization-service/src/main/java/gov/cdc/etldatapipeline/organization/config/KafkaConsumerConfig.java
- person-service/src/main/java/gov/cdc/etldatapipeline/person/config/KafkaConsumerConfig.java
Spring Kafka warns when a `@KafkaListener` returns `Future/CompletableFuture` but the container is not configured for async acks, leading to immediate ack before async work completes.
Set `factory.getContainerProperties().setAsyncAcks(true)` on the kafkaListenerContainerFactory to defer commits until the future completes.
- **Related story**: [CNDE-3156](https://cdc-nbs.atlassian.net/browse/CNDE-3156)
> CNDE-3156: RTR - Kafka - Enable async acks for future-returning listeners
